// Generated by scripts/sync-hkustsu-clubs.mjs from the HKUST Students' Union society directory. Do not edit by hand.
export const clubsData = {
  "source": {
    "url": "https://hkustsu.hkust.edu.hk/societies",
    "retrieved_at": "2026-10-04T11:04:01.374Z",
    "sha256": "2b95619ce1a1a391ed9bc243de7662ceeb1640747e89f1940ccd31b9807fbf68"
  },
  "clubs": [
    {
      "id": "su-5",
      "name": "Art Club",
      "category": "culture",
      "tags": "文化艺术",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/5",
      "summary": ""
    },
    {
      "id": "su-6",
      "name": "Chinese Folk Art Society",
      "category": "culture",
      "tags": "文化艺术",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/6",
      "summary": "Chinese Folk Art Society, HKUSTSU, abbreviated as CFAS, with a history spannin…"
    },
    {
      "id": "su-7",
      "name": "Chinese Orchestra",
      "category": "culture",
      "tags": "文化艺术",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/7",
      "summary": "The Chinese Orchestra, HKUSTSU, also known as the HKUST Chinese Orchestra, was…"
    },
    {
      "id": "su-8",
      "name": "Drama Society",
      "category": "culture",
      "tags": "文化艺术",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/8",
      "summary": "The Drama Society of the HKUSTSU is a student-run organization dedicated to pr…"
    },
    {
      "id": "su-9",
      "name": "Film Society",
      "category": "culture",
      "tags": "文化艺术",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/9",
      "summary": "Film Society shines like a brilliant star, illuminating the hearts of movie lo…"
    },
    {
      "id": "su-10",
      "name": "South Asian Students’ Association",
      "category": "culture",
      "tags": "文化艺术",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/10",
      "summary": "The South Asian Students' Society (SASS) at HKUST is a student-led organizatio…"
    },
    {
      "id": "su-11",
      "name": "Southeast Asian Students’ Society",
      "category": "culture",
      "tags": "文化艺术",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/11",
      "summary": "The South East Asian Student Association is part of HKUST and was founded in 2…"
    },
    {
      "id": "su-12",
      "name": "The Band Society",
      "category": "culture",
      "tags": "文化艺术",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/12",
      "summary": "The Band Society, HKUSTSU (香港科技大學學生會凝音社) is a vibrant student-led society dedi…"
    },
    {
      "id": "su-13",
      "name": "The University Choir",
      "category": "culture",
      "tags": "文化艺术",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/13",
      "summary": "Established in 1994, The University Choir, HKUSTSU, is dedicated to promote ch…"
    },
    {
      "id": "su-14",
      "name": "University Philharmonic Orchestra",
      "category": "culture",
      "tags": "文化艺术",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/14",
      "summary": "The University Philharmonic Orchestra (UPO), HKUSTSU, is a student-led society…"
    },
    {
      "id": "su-148",
      "name": "Comics and Animation Society",
      "category": "culture",
      "tags": "文化艺术",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/148",
      "summary": "Comics and Animation Society aims to promote anime, doujin, and cosplay cultur…"
    },
    {
      "id": "su-155",
      "name": "Indonesian Students’ Association (MUSTI)",
      "category": "culture",
      "tags": "文化艺术",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/155",
      "summary": "Indonesian Students’ Association (MUSTI), HKUSTSU"
    },
    {
      "id": "su-28",
      "name": "Sports Association",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/28",
      "summary": ""
    },
    {
      "id": "su-29",
      "name": "Archery Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/29",
      "summary": "Draw. Aim. Release."
    },
    {
      "id": "su-30",
      "name": "Dance Society",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/30",
      "summary": "Founded over 30 years, the Dance Society acts as one of the Sports Association…"
    },
    {
      "id": "su-31",
      "name": "Distance Runner’s Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/31",
      "summary": ""
    },
    {
      "id": "su-32",
      "name": "Dodgeball Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/32",
      "summary": "The HKUST Dodgeball Club was founded in 2017 and aims to increase students’ aw…"
    },
    {
      "id": "su-33",
      "name": "Dragon Boat Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/33",
      "summary": "The HKUST Dragon Boat Team, with its rich history dating back to 1996, has bee…"
    },
    {
      "id": "su-34",
      "name": "Fencing Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/34",
      "summary": ""
    },
    {
      "id": "su-35",
      "name": "Judo Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/35",
      "summary": ""
    },
    {
      "id": "su-36",
      "name": "Kendo Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/36",
      "summary": "The UST Kendo Club is open to everyone"
    },
    {
      "id": "su-37",
      "name": "Korfball Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/37",
      "summary": ""
    },
    {
      "id": "su-38",
      "name": "Rope Skipping Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/38",
      "summary": ""
    },
    {
      "id": "su-39",
      "name": "Rowing Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/39",
      "summary": "Whether you want a relaxing weekly exercise or high-level competition, our Row…"
    },
    {
      "id": "su-40",
      "name": "Rugby Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/40",
      "summary": ""
    },
    {
      "id": "su-41",
      "name": "Shaolin Martial Arts Society",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/41",
      "summary": "Join us to learn traditional Shaolin martial art and free fighting skills! 一齊入…"
    },
    {
      "id": "su-42",
      "name": "Softball Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/42",
      "summary": ""
    },
    {
      "id": "su-43",
      "name": "Sport Climbing Students’ Society",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/43",
      "summary": ""
    },
    {
      "id": "su-44",
      "name": "Squash Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/44",
      "summary": "Squash is an exhilarating, fast-paced sport that Forbes Magazine once rated th…"
    },
    {
      "id": "su-45",
      "name": "Student Basketball Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/45",
      "summary": ""
    },
    {
      "id": "su-46",
      "name": "Students’ Badminton Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/46",
      "summary": ""
    },
    {
      "id": "su-47",
      "name": "Students’ Football Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/47",
      "summary": ""
    },
    {
      "id": "su-48",
      "name": "Students’ Karate Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/48",
      "summary": ""
    },
    {
      "id": "su-49",
      "name": "Students’ Swimming Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/49",
      "summary": ""
    },
    {
      "id": "su-50",
      "name": "Table Tennis Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/50",
      "summary": ""
    },
    {
      "id": "su-51",
      "name": "Tai Chi Society",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/51",
      "summary": "學會巧勁，勝用蠻力！Explore the subtlety of using power through Taichi !"
    },
    {
      "id": "su-52",
      "name": "Tchoukball Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/52",
      "summary": "Tchoukball is an indoor team sport, with seven team players on the court playi…"
    },
    {
      "id": "su-53",
      "name": "The Netball Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/53",
      "summary": "Join the Netball Club – All Skills Welcome!"
    },
    {
      "id": "su-54",
      "name": "The Student Tennis Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/54",
      "summary": ""
    },
    {
      "id": "su-55",
      "name": "Track and Field Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/55",
      "summary": "Welcome to the ultimate athletics community at HKUST! The Track & Field Club a…"
    },
    {
      "id": "su-56",
      "name": "Volleyball Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/56",
      "summary": "== English Version Below =="
    },
    {
      "id": "su-57",
      "name": "Wing Chun Martial Arts Society",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/57",
      "summary": "Have you ever seen the kung fu movie《Ip Man》? Themartial art used in the movie…"
    },
    {
      "id": "su-150",
      "name": "Taekwondo Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/150",
      "summary": "Welcome to the HKUST Taekwondo Club! Taekwondo is a well-known Korean martial …"
    },
    {
      "id": "su-152",
      "name": "Competitive Cheerleading Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/152",
      "summary": "Cheerleading is a dynamic and high-energy sport that takes athleticism, teamwo…"
    },
    {
      "id": "su-161",
      "name": "Cricket Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/161",
      "summary": "HKUST Cricket Club is the most successful university cricket team in Hong Kong…"
    },
    {
      "id": "su-162",
      "name": "Handball Club",
      "category": "sport",
      "tags": "运动",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/162",
      "summary": ""
    },
    {
      "id": "su-15",
      "name": "Bible Education and Exploration Society",
      "category": "interest",
      "tags": "兴趣与信仰",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/15",
      "summary": "Greetings from Bible Education and Exploration Society!"
    },
    {
      "id": "su-16",
      "name": "Campus Crusade for Christ",
      "category": "interest",
      "tags": "兴趣与信仰",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/16",
      "summary": "得著科大 | 改變世界    Win the Campus, Change the World"
    },
    {
      "id": "su-17",
      "name": "China Entrepreneur Network",
      "category": "interest",
      "tags": "兴趣与信仰",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/17",
      "summary": "The China Entrepreneur Network (CEN) is a university-based, student-run organi…"
    },
    {
      "id": "su-18",
      "name": "Christian Choir",
      "category": "interest",
      "tags": "兴趣与信仰",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/18",
      "summary": "Christian Choir was officially established in March 2014 with its vision to eq…"
    },
    {
      "id": "su-19",
      "name": "Contract Bridge Club",
      "category": "interest",
      "tags": "兴趣与信仰",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/19",
      "summary": "We hold regular bridge sessions for hkust members to learn and play bridge. An…"
    },
    {
      "id": "su-20",
      "name": "Debating Society",
      "category": "interest",
      "tags": "兴趣与信仰",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/20",
      "summary": ""
    },
    {
      "id": "su-21",
      "name": "Games Society",
      "category": "interest",
      "tags": "兴趣与信仰",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/21",
      "summary": ""
    },
    {
      "id": "su-23",
      "name": "People’s Campus Radio",
      "category": "interest",
      "tags": "兴趣与信仰",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/23",
      "summary": "The 1st Live Online Broadcasting Campus Radio in Asia!"
    },
    {
      "id": "su-24",
      "name": "Rotaract Club of HKUST",
      "category": "interest",
      "tags": "兴趣与信仰",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/24",
      "summary": "Rotaract Club of HKUST, HKUSTSU"
    },
    {
      "id": "su-25",
      "name": "Student Astronomy Club",
      "category": "interest",
      "tags": "兴趣与信仰",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/25",
      "summary": "Who are we?"
    },
    {
      "id": "su-27",
      "name": "University YMCA – HKUST",
      "category": "interest",
      "tags": "兴趣与信仰",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/27",
      "summary": "Since 2003, the University & College YMCA Department of Chinese YMCA of Hong K…"
    },
    {
      "id": "su-149",
      "name": "Mahjong Research Society",
      "category": "interest",
      "tags": "兴趣与信仰",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/149",
      "summary": "𝙃𝙞, 𝙬𝙚 𝙖𝙧𝙚 𝙩𝙝𝙚 𝙈𝙖𝙝𝙟𝙤𝙣𝙜 𝙍𝙚𝙨𝙚𝙖𝙧𝙘𝙝 𝙎𝙤𝙘𝙞𝙚𝙩𝙮, 𝙃𝙆\ud835…"
    },
    {
      "id": "su-151",
      "name": "Christian Fellowship",
      "category": "interest",
      "tags": "兴趣与信仰",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/151",
      "summary": "Christian Fellowship was established in 1991. We are a group of Christians fro…"
    },
    {
      "id": "su-154",
      "name": "Muslim Society",
      "category": "interest",
      "tags": "兴趣与信仰",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/154",
      "summary": "Assalamu alaikum (Peace be upon you all)!"
    },
    {
      "id": "su-156",
      "name": "Catholic Society",
      "category": "interest",
      "tags": "兴趣与信仰",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/156",
      "summary": "The HKUST Catholic Society, established in 1992, has long served as a communit…"
    },
    {
      "id": "su-158",
      "name": "AIESEC",
      "category": "interest",
      "tags": "兴趣与信仰",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/158",
      "summary": "AIESEC is the world’s largest international youth-run organization, having bra…"
    },
    {
      "id": "su-4",
      "name": "The Engineering Students' Union",
      "category": "school",
      "tags": "学院学生会",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/4",
      "summary": "香港科技大學學生會工學院學生會(ESU) 是一個在香港科技大學的非牟利學生團體。ESU代表逾3000名就讀科大的工程學系的本科生及研究生。"
    },
    {
      "id": "su-62",
      "name": "The Business Students’ Union",
      "category": "school",
      "tags": "学院学生会",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/62",
      "summary": "The Business Students’ Union, HKUSTSU (hereafter BSU) is a student-run, non-po…"
    },
    {
      "id": "su-64",
      "name": "The Humanities and Social Science Students’ Union",
      "category": "school",
      "tags": "学院学生会",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/64",
      "summary": ""
    },
    {
      "id": "su-65",
      "name": "Accounting Students’ Society",
      "category": "department",
      "tags": "系会",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/65",
      "summary": "Accounting Students' Society, HKUSTSU was founded in 1992. It is one of the ea…"
    },
    {
      "id": "su-66",
      "name": "The Economics Students’ Society",
      "category": "department",
      "tags": "系会",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/66",
      "summary": "Established in 1992, The Economics Students’ Society, HKUSTSU have been strivi…"
    },
    {
      "id": "su-67",
      "name": "The Finance Students' Society",
      "category": "department",
      "tags": "系会",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/67",
      "summary": ""
    },
    {
      "id": "su-69",
      "name": "Industrial Engineering and Decision Analytics Students’ Society",
      "category": "department",
      "tags": "系会",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/69",
      "summary": "we aim to foster a supportive and dynamic community that enhances both academi…"
    },
    {
      "id": "su-70",
      "name": "The Chemical and Biological Engineering Students’ Society",
      "category": "department",
      "tags": "系会",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/70",
      "summary": "As the Chemical and Biological Engineering Student Society (CBESS) at the Hong…"
    },
    {
      "id": "su-71",
      "name": "The Civil and Environmental Engineering Students’ Society",
      "category": "department",
      "tags": "系会",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/71",
      "summary": ""
    },
    {
      "id": "su-72",
      "name": "The Computer Science and Engineering Students’ Society",
      "category": "department",
      "tags": "系会",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/72",
      "summary": "The Computer Science and Engineering Students' Society, Hong Kong University o…"
    },
    {
      "id": "su-73",
      "name": "The Electronic and Computer Engineering Students’ Society",
      "category": "department",
      "tags": "系会",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/73",
      "summary": "The Electronic and Computer Engineering Students' Society, Hong Kong Universit…"
    },
    {
      "id": "su-74",
      "name": "Integrative Systems and Design Students’ Society",
      "category": "department",
      "tags": "系会",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/74",
      "summary": "ISD, or Integrative Systems and Design, combines design thinking, problem-solv…"
    },
    {
      "id": "su-75",
      "name": "Biochemistry and Biotechnology Students’ Society",
      "category": "department",
      "tags": "系会",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/75",
      "summary": "Hello! We are the Biochemistry and Biotechnology Students' Society, HKUSTSU. F…"
    },
    {
      "id": "su-76",
      "name": "International Research Enrichment Students’ Society",
      "category": "department",
      "tags": "系会",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/76",
      "summary": "🧐IRESS係咩嚟？🧐"
    },
    {
      "id": "su-77",
      "name": "Biology and Biotechnology Students’ Society",
      "category": "department",
      "tags": "系会",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/77",
      "summary": "Established for over 35 years, the Biology and Biotechnology Students’ Society…"
    },
    {
      "id": "su-78",
      "name": "Environmental Management and Technology Students’ Society",
      "category": "department",
      "tags": "系会",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/78",
      "summary": "The Environmental Management and Technology Students' Society is the departmen…"
    },
    {
      "id": "su-60",
      "name": "Glacier, HOUSE III SA",
      "category": "house",
      "tags": "舍堂",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/60",
      "summary": "香港科技大學學生會冰川社三學生會"
    },
    {
      "id": "su-61",
      "name": "Vista, House IV Students’ Association",
      "category": "house",
      "tags": "舍堂",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/61",
      "summary": ""
    },
    {
      "id": "su-147",
      "name": "Endeavour, House V Students' Association",
      "category": "house",
      "tags": "舍堂",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/147",
      "summary": "社五卓毅（HouseV）💛係hall V嘅宿生會，平日會為大家提供生活上嘅便利同小福利，繁忙的學習中點可以少咗一片用來釋放壓力嘅淨土呢？我哋除咗開學迎接新…"
    },
    {
      "id": "su-160",
      "name": "VERTEX, House II Students' Association.",
      "category": "house",
      "tags": "舍堂",
      "url": "https://hkustsu.hkust.edu.hk/societies/about/160",
      "summary": ""
    }
  ]
} as const;
