import {beforeEach,afterEach,it,expect} from 'vitest';
import {mkdtempSync,readFileSync,rmSync} from 'node:fs';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {randomUUID} from 'node:crypto';
import {createProductApp} from '../src/product/app.js';
import {publicActivity,publicActivities} from '../apps/hub/lib/public-activities';
let app:ReturnType<typeof createProductApp>,dir:string,credential:string,config:{enabled:boolean;origin:string;apiBase:string};
beforeEach(async()=>{dir=mkdtempSync(join(tmpdir(),'campus-share-'));app=createProductApp({dataDir:dir});config={enabled:true,origin:'http://127.0.0.1:3000',apiBase:(await app.listen({host:'127.0.0.1',port:0}))+'/api/v1'};const challenge=(await app.inject({method:'POST',url:'/api/v1/auth/email/challenges',payload:{email:'share@example.test'}})).json().data;const {code}=JSON.parse(readFileSync(join(dir,'mail',challenge.challenge_id+'.json'),'utf8'));credential=(await app.inject({method:'POST',url:'/api/v1/auth/email/verify',payload:{challenge_id:challenge.challenge_id,code}})).json().data.access_token;});
afterEach(async()=>{await app.close();rmSync(dir,{recursive:true,force:true});});
async function create(visibility:string){const now=Date.now();return(await app.inject({method:'POST',url:'/api/v1/activities',headers:{authorization:'Bearer '+credential,'idempotency-key':randomUUID()},payload:{kind:'study',title:visibility+' title',location:'Library',starts_at:new Date(now+86400000).toISOString(),ends_at:new Date(now+90000000).toISOString(),capacity:4,languages:['en'],interaction:'quiet',visibility}})).json().data;}
it('fetches only guest/public data and cannot widen visibility with session state',async()=>{const pub=await create('public'),privateEvent=await create('members');expect((await publicActivity(config,pub.id)).mine).toBeNull();await expect(publicActivity(config,privateEvent.id)).rejects.toMatchObject({status:404});expect((await publicActivities(config)).items.map(a=>a.id)).toEqual([pub.id]);});
it('re-reads deletion/cancellation, rejects path injection and reports backend failure without a stale preview',async()=>{const pub=await create('public');await publicActivity(config,pub.id);await app.inject({method:'POST',url:`/api/v1/activities/${pub.id}/cancel`,headers:{authorization:'Bearer '+credential},payload:{version:1}});expect((await publicActivity(config,pub.id)).status).toBe('cancelled');expect((await publicActivities(config)).items).toEqual([]);await app.inject({method:'DELETE',url:`/api/v1/activities/${pub.id}`,headers:{authorization:'Bearer '+credential},payload:{version:2}});await expect(publicActivity(config,pub.id)).rejects.toMatchObject({status:404});await expect(publicActivity(config,'../me/export')).rejects.toMatchObject({status:404});await app.close();await expect(publicActivities(config)).rejects.toMatchObject({status:503});});
