// Generated by scripts/sync-cso-dining.mjs from the CSO restaurants page. Do not edit by hand.
export const diningData = {
  "source": {
    "url": "https://cso.hkust.edu.hk/index.php/locations/restaurants",
    "special_hours": "https://cso.hkust.edu.hk/special-opening-hours",
    "retrieved_at": "2026-10-04T16:22:05.775Z",
    "sha256": "694854de66cf291d6364a674bfc0d3a386c7126c0f13c499f2cfa6590a8aa1ef"
  },
  "outlets": [
    {
      "id": "american-diner",
      "name": "American Diner",
      "category": "Fast Food",
      "phone": "pat@thesandwichclub.com.hk",
      "hours": [
        "Monday - Friday 08:00 - 21:00 (Last Order: 20:45)",
        "Saturday 08:00 - 18:00 (Last Order: 17:45)",
        "Sunday 11:00 - 18:00 (Last Order: 17:45)",
        "PH - Closed"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?id=685ceb0b07973ca98d5226b0&building_floor_id=bf0000000000000000000108",
      "menu": "https://cso.hkust.edu.hk/sites/default/files/2024-07/AmericanDiner%20Menu_Eng_Chin_2024-07-22-2_1.pdf",
      "about": "If you are looking for the value-for-money options on campus, American Diner is the one you can choose. It provides a wide variety of Western fast food such as burger, hot dogs, spaghetti, panini as well as other snacks "
    },
    {
      "id": "asia-pacific-catering",
      "name": "Asia Pacific Catering",
      "category": "Fast Food",
      "phone": "2243 1087 / 2243 1287",
      "hours": [
        "Monday - Saturday 07:30 - 21:00 (Last Order: 20:45)",
        "Sunday & PH 09:00 - 21:00 (Last Order: 20:45)"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?id=6a79542a745fdf07f23d73b9&building_floor_id=bf0000000000000000000101",
      "menu": "https://cso.hkust.edu.hk/sites/default/files/2025-08/APC%20Menu%202025_06.pdf",
      "about": "This Kitchen offers a menu which is highly adopted to local's taste with some dishes changed from time to time according to season & occasion."
    },
    {
      "id": "can-teen-ii",
      "name": "Can.teen II",
      "category": "Fast Food",
      "phone": "2358 3123",
      "hours": [
        "Sunday - Saturday & PH 07:30 - 21:00 (Last Order: 20:45)"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?id=6858df71f5e020372bc4091b&building_floor_id=bf0000000000000000000106",
      "menu": null,
      "about": "Embellished with a minimalist and modern design, the casual diners’ experience at the new LG1 Restaurant is taken to a whole new level. You will find your much-loved food served up in one convenient location. Boasting a "
    },
    {
      "id": "china-garden",
      "name": "China Garden",
      "category": "Table Service Restaurant",
      "phone": "2358 1133",
      "hours": [
        "Monday - Saturday 11:00 - 22:00 (Last Order: 21:30)",
        "Sunday & PH 10:30 - 22:00 (Last Order: 21:30)"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?id=6858defff5e020372bc3d4af&building_floor_id=bf0000000000000000000107",
      "menu": "https://cso.hkust.edu.hk/sites/default/files/2026-08/China%20Garden%20Full%20Menu_2026-08.pdf",
      "about": "The G/F Restaurant is a bookable venue which provides full table service with a comprehensive seasonal menu of Chinese dishes and other special functions, including cocktail receptions, banquets and buffets. This premise"
    },
    {
      "id": "donburi-bowl",
      "name": "Donburi Bowl",
      "category": "Grab & Go",
      "phone": null,
      "hours": [
        "Monday - Friday 11:00 - 14:00 (while stocks last)",
        "PH - Closed"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?id=698177859bc90e21e496310f&building_floor_id=bf0000000000000000000109",
      "menu": "https://cso.hkust.edu.hk/sites/default/files/2026-08/DONBURI%20Bowls%20Menu.pdf",
      "about": null
    },
    {
      "id": "ebeneezer-s",
      "name": "Ebeneezer's",
      "category": "Grab & Go",
      "phone": "3188 5550 (Email: uni@ebeneezers.com)",
      "hours": [
        "Monday - Saturday 10:00 - 22:00 (Last Order: 21:30)",
        "Sunday & PH - 10:00 - 20:00 (Last Order: 19:30)"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?id=6858e0abf5e020372bc4343c&building_floor_id=bf0000000000000000000401",
      "menu": "https://cso.hkust.edu.hk/sites/default/files/2026-08/Ebeneezers_Menu_2026-Sep.pdf",
      "about": "Operated by the Ebeneezer's, one of the experienced and certified Halal food operators in town specializing in a variety of kebabs, Indian curries, biryanis and pizzas, etc."
    },
    {
      "id": "gold-rice-bowl",
      "name": "Gold Rice Bowl",
      "category": "Fast Food",
      "phone": "2325 2533",
      "hours": [
        "Sunday - Saturday & PH 11:00 - 21:00 (Last Order: 20:45)"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?id=6858df47f5e020372bc3f1a3&building_floor_id=bf0000000000000000000101",
      "menu": "https://cso.hkust.edu.hk/sites/default/files/2024-08/GRB%20Menu%202024-09.pdf",
      "about": "This kitchen serves different types of South East Asian cuisine, where customers can indulge in a variety of dishes from Sichuan, Shanghai, Japanese and Hong Kong - fusion of Chinese and Western influences. It also offer"
    },
    {
      "id": "hft-life",
      "name": "HFT Life",
      "category": "Grab & Go",
      "phone": "2557 4828",
      "hours": [
        "Monday - Friday 07:30 - 19:00",
        "Saturday , Sunday & PH: 08:00 - 19:00"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?id=68b803f5d5ae9906e363dabf&building_floor_id=bf0000000000000000000301",
      "menu": "https://cso.hkust.edu.hk/sites/default/files/2026-08/HFT%20Lift_UST_Product%20list_Aug%202026.pdf",
      "about": "\"HFT Life\" is a brand-new concept store introduced by the Hung Fook Tong 鴻福堂, a retail chain specializing in Chinese herbal teas, soups, and healthy food. \"HFT Life\" aims to bring together Chinese and western food cultur"
    },
    {
      "id": "joa",
      "name": "JoA",
      "category": "Fast Food",
      "phone": null,
      "hours": [
        "Monday - Saturday 10:00 - 21:00 (Last Order: 20:30) Break between 15:00-17:00 until 20 Sep 2026",
        "Sunday & PH: - Closed"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?id=685ceb0b07973ca98d5226a6&building_floor_id=bf0000000000000000000108",
      "menu": "https://cso.hkust.edu.hk/sites/default/files/2026-08/JoA%20Menu_2026-09.pdf",
      "about": null
    },
    {
      "id": "mccafe",
      "name": "McCafe",
      "category": "Cafe",
      "phone": "2358 0271",
      "hours": [
        "Sunday - Saturday 07:00 - 24:00",
        "PH: 07:00 - 24:00"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?id=6858df52f5e020372bc3f74c&building_floor_id=bf0000000000000000000103",
      "menu": null,
      "about": "It serves Espresso Coffees, Iced Coffees, Teas and Frappés... don't forget to enjoy with the featured cakes, Ciabatta and selected bakeries."
    },
    {
      "id": "mcdonald-s",
      "name": "McDonald's",
      "category": "Fast Food",
      "phone": "2358 0271",
      "hours": [
        "Sunday - Saturday & PH 07:00 - 24:00"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?id=6858df52f5e020372bc3f74c&building_floor_id=bf0000000000000000000103",
      "menu": null,
      "about": "It serves burgers, French fries, fried chicken wings, extra value breakfast & extra value meal."
    },
    {
      "id": "nourish-n-go-green",
      "name": "Nourish N' Go Green",
      "category": "Grab & Go",
      "phone": "66116476",
      "hours": [
        "Sunday - Saturday 11:00 - 21:00"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?id=69201f407e880f07eea920ea&building_floor_id=69201f38923bee03b589d91b",
      "menu": "https://cso.hkust.edu.hk/sites/default/files/2025-11/nng_menu.pdf",
      "about": null
    },
    {
      "id": "oliver-s-super-sandwiches",
      "name": "Oliver's Super Sandwiches",
      "category": "Fast Food",
      "phone": "2397 1119",
      "hours": [
        "Monday - Friday 07:30 - 19:30 (Last Order: 19:15)",
        "Saturday , Sunday & PH 11:00 - 19:00 (Last Order: 18:45)"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?id=6858df47f5e020372bc3f54e&building_floor_id=bf0000000000000000000101",
      "menu": "https://cso.hkust.edu.hk/sites/default/files/2025-10/OSS%20-%20Full%20Menu_2025-09.pdf",
      "about": "Oliver's Super Sandwiches located in the new extension of the LG7 canteen, well-known for its freshly made sandwiches, light pasta, salads and baked potatoes with a variety of toppings, etc."
    },
    {
      "id": "pacific-coffee",
      "name": "Pacific Coffee",
      "category": "Cafe",
      "phone": "5162 5103",
      "hours": [
        "Monday - Friday 08:00 - 18:30",
        "Saturday 08:00 - 17:00",
        "Sunday & PH - Closed"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?id=6858e0aaf5e020372bc43420&building_floor_id=bf0000000000000000000401",
      "menu": "https://cso.hkust.edu.hk/sites/default/files/2024-09/Pacific%20Coffee%20-%202024%20Sep-3.pdf",
      "about": "Operated by the Pacific Coffee Company Limited , The Coffee Corner dishes up a wide array of fare; from muffins and different types of pastry in the morning, through to Panini, packed salad and more for lunch and dinner."
    },
    {
      "id": "passione",
      "name": "Passione",
      "category": "Cafe",
      "phone": "2811 1243",
      "hours": [
        "Monday - Friday 07:30 - 20:00 (Last Order for Hot Meal: 19:30)",
        "Saturday 07:30 - 18:00 (Last Order for Hot Meal: 17:30)",
        "Sunday & PH - Closed"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?id=685ceb0b07973ca98d522674&building_floor_id=bf0000000000000000000108",
      "menu": "https://cso.hkust.edu.hk/sites/default/files/2026-07/Passione%20-%20Full%20Menu_2026-06.pdf",
      "about": "The name of the shop Passione echoes the lifelong passion of owner Gerard Dubois, a Swiss-born pastry chef, for delivering top-quality products. Here, patrons seeking a traditional French cafe experience can sit back to "
    },
    {
      "id": "seafront-cafeteria",
      "name": "Seafront Cafeteria",
      "category": "Fast Food",
      "phone": "9055 9306 or 9487 0417",
      "hours": [
        "Sunday - Friday 17:00 - 00:30 (Last Order: 00:15)",
        "Saturday & PH - Closed"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?remote_id=UG06G001",
      "menu": null,
      "about": "Located in Hall VI, Delicious is a friendly and attentive food counter, offers a comforting and relaxed environmebt that feels like a home away from home dining experience. It serves different types of traditional Hong K"
    },
    {
      "id": "starbucks-coffee",
      "name": "Starbucks Coffee",
      "category": "Cafe",
      "phone": "2798 6208",
      "hours": [
        "Monday - Friday 08:00 - 20:00",
        "Sunday - Saturday 08:30 - 19:00",
        "PH: 08:30 - 19:00"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?keyword=Canteen&id=6858defff5e020372bc3d7bb&building_floor_id=bf0000000000000000000107",
      "menu": "https://cso.hkust.edu.hk/sites/default/files/2026-08/Starbucks-Summer%20Beverage_Food%20Menu_2026-09.pdf",
      "about": null
    },
    {
      "id": "subway",
      "name": "Subway",
      "category": "Grab & Go",
      "phone": "2324 3600 (Email: info@subwayhongkong.com)",
      "hours": [
        "Monday - Friday 08:00 - 20:00",
        "Saturday , Sunday & PH: 09:00 - 19:00"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?id=6858df7cf5e020372bc4131c&building_floor_id=bf0000000000000000000201",
      "menu": "https://cso.hkust.edu.hk/sites/default/files/2026-07/Subway%20Menu%20-%202026-07-03.pdf",
      "about": "All sandwiches are prepared on a variety of freshly baked breads, with your choice of cold cuts or Veggie Delite. Top off your selection with your choice of vegetables and condiments. Moreover, you can check out in-depth"
    },
    {
      "id": "tamjai-samgor",
      "name": "TamJai SamGor",
      "category": "Fast Food",
      "phone": "2690 9138",
      "hours": [
        "Sunday - Saturday & PH 11:00 - 21:00 (Last Order: 20:45)"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?id=6858df47f5e020372bc3f512&building_floor_id=bf0000000000000000000101",
      "menu": null,
      "about": "TamJai SamGor (譚仔三哥) is known for its delicious mixian and an array of flavors that let you tailor your meal to perfection. You can choose from a variety of savory sauces and fresh ingredients like Tofu Puffs, Shiitake M"
    },
    {
      "id": "the-unibar",
      "name": "The UniBar",
      "category": "Table Service Restaurant",
      "phone": "2363 6638",
      "hours": [
        "Sunday - Saturday 16:00 - 11:00 (Last Order: 22:30)",
        "PH: 16:00 - 11:00 (Last Order: 22:30)"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?id=6858e0f2f5e020372bc44c11&building_floor_id=bf0000000000000000000601",
      "menu": "https://cso.hkust.edu.hk/sites/default/files/2026-08/UniBar%20-%20Drink%20Menu_2026-09.pdf",
      "about": "All the while, the Unibar will offer tempting food choices, a variety of mocktails to complement the traditional bar all of which can be enjoyed whilst watching a variety of live and rerun sports games including English "
    },
    {
      "id": "unibistro",
      "name": "UniBistro",
      "category": "Table Service Restaurant",
      "phone": "2363 6638",
      "hours": [
        "Sunday - Saturday 12:00 noon - 21:00 (Last Order: 20:30)",
        "PH: 12:00 noon - 21:00 (Last Order: 20:30)"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?id=6858e0f2f5e020372bc44c07&building_floor_id=bf0000000000000000000601",
      "menu": "https://cso.hkust.edu.hk/sites/default/files/2026-08/UniBistro%20A%20La%20Carte%20Menu%202025%20V1_2026-09.pdf",
      "about": "The restaurant and bar will offer a predominantly Mediterranean cuisine including a daily salad bar with pasta or pizza. In the evening the restaurant and bar will also offer tempting food choices, a variety of mocktails"
    },
    {
      "id": "unique",
      "name": "UniQue",
      "category": "Table Service Restaurant",
      "phone": "3701 8822",
      "hours": [
        "Sunday - Saturday 07:30 - 15:00 (Last Order: 14:30)",
        "PH: 07:30 - 15:00 (Last Order: 14:30)"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?remote_id=CL2LOUNGE",
      "menu": "https://cso.hkust.edu.hk/sites/default/files/2026-08/UniQue%20Menu_Aug%2024%20-%20Sep%204%2C%202026%20Bfast%20A%20%26%20B_Set%20Lunch%2090.pdf",
      "about": "A stylish restaurant with panoramic sea views, a sensational bar and a patio for al fresco dining, UniQue acts as a faculty clubhouse, providing a casual, friendly ambiance for university academics, staff and guests. The"
    },
    {
      "id": "univeggie-this-this-rice",
      "name": "UniVeggie & This This Rice",
      "category": "Grab & Go",
      "phone": null,
      "hours": [
        "Monday - Friday 11:00 - 14:00 (while stocks last)",
        "PH - Closed"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?id=6981771bca4ca721cad82cc8&building_floor_id=bf0000000000000000000103",
      "menu": null,
      "about": null
    },
    {
      "id": "webite-space",
      "name": "WeBite Space",
      "category": "Fast Food",
      "phone": null,
      "hours": [
        "Monday - Friday 07:30 - 21:00 (Last Order: 20:45)",
        "Sunday - Saturday 08:00 - 21:00 (Last Order: 20:45)",
        "PH: 08:00 - 21:00 (Last Order: 20:45)"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?id=6858e0aaf5e020372bc43395&building_floor_id=bf0000000000000000000401",
      "menu": "https://cso.hkust.edu.hk/sites/default/files/2026-08/WeBite%20Menu_2026-09.pdf",
      "about": null
    },
    {
      "id": "hana-musubi",
      "name": "華御結 Hana-musubi",
      "category": "Grab & Go",
      "phone": null,
      "hours": [
        "Sunday - Saturday 08:00 - 20:00",
        "PH: 08:00 - 20:00"
      ],
      "path_advisor": "https://navigate.ust.hk/path/app/location/id?id=6a8556b674fe9a9580306ff4&building_floor_id=bf0000000000000000000202",
      "menu": null,
      "about": null
    }
  ]
} as const;
