import {createHash,randomUUID} from 'node:crypto';
import type {DatabaseSync} from 'node:sqlite';
import {z} from 'zod';
import {transaction} from '../database.js';
import {ApiError} from '../errors.js';
import {targetSchema,type createDirectoryStore} from './directory.js';
import {shuttleData} from './shuttle-data.js';
const bilingual=z.object({zh:z.string().trim().min(1).max(2000),en:z.string().trim().min(1).max(2000)}).strict();
const officialLink=z.string().url().max(2000).refine(value=>{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password&&['hkust.edu.hk','ust.hk'].some(host=>u.hostname===host||u.hostname.endsWith('.'+host));});
export const placeEditSchema=z.object({version:z.number().int().positive(),source_check_id:z.string().uuid(),reason:z.string().trim().min(5).max(1000),fields:z.object({name:bilingual,location:bilingual,description:bilingual,published_hours:bilingual,map_url:officialLink.nullable(),action_url:officialLink}).strict()}).strict();
const maintenanceTarget=targetSchema.extend({target_kind:z.enum(['place','shuttle','shuttle_timetable','shuttle_holidays'])});
type Check={id:string;target_kind:'place'|'shuttle'|'shuttle_timetable'|'shuttle_holidays';target_id:string;url:string;sha256:string;retrieved_at:number};
type Correction={id:string;owner_id:string;target_kind:'place'|'shuttle';target_id:string;message:string;status:string;resolution:string;created_at:number;version:number;reviewed_at:number|null};
export function createMaintenanceStore(db:DatabaseSync,directory:ReturnType<typeof createDirectoryStore>,now:()=>number,fetchSource:typeof fetch=fetch){
 const stale=()=>new ApiError(409,'VERSION_CONFLICT','Refresh the record before saving.');
 const target=(input:unknown)=>{const value=maintenanceTarget.parse(input);if(value.target_kind==='shuttle_timetable'&&value.target_id==='catalog')return {value,url:shuttleData.source.url};if(value.target_kind==='shuttle_holidays'&&value.target_id==='calendar')return {value,url:shuttleData.holiday_source.url};if(!['place','shuttle'].includes(value.target_kind))throw new ApiError(404,'SOURCE_NOT_FOUND','Unknown source.');if(value.target_kind==='place')return {value,url:directory.entry(value.target_id).source.url};if(!shuttleData.routes.some(r=>r.id===value.target_id))throw new ApiError(404,'ROUTE_NOT_FOUND','Unknown reviewed route.');return {value,url:shuttleData.source.url};};
 function listCorrections(input:unknown){const q=z.object({status:z.enum(['pending','resolved','rejected']).default('pending'),limit:z.coerce.number().int().min(1).max(50).default(20),cursor:z.string().uuid().optional()}).strict().parse(input);const rows=db.prepare('SELECT id,owner_id,target_kind,target_id,message,status,resolution,created_at,version,reviewed_at FROM campus_corrections WHERE status=? AND id>? ORDER BY id LIMIT ?').all(q.status,q.cursor??'',q.limit+1) as Correction[];return {items:rows.slice(0,q.limit),next_cursor:rows.length>q.limit?rows[q.limit-1].id:null};}
 async function checkSource(actor:string,input:unknown){
  const {value,url}=target(input);
  const count=db.prepare('SELECT COUNT(*) AS n FROM campus_source_checks WHERE actor_id=? AND retrieved_at>?').get(actor,now()-3600000) as {n:number};if(count.n>=30)throw new ApiError(429,'SOURCE_CHECK_LIMIT','At most 30 source checks per hour.');
  const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);
  let body:Buffer;
  try{
   const response=await fetchSource(url,{redirect:'error',signal:controller.signal,headers:{accept:'text/html,text/plain,application/pdf'}});
   if(!response.ok||response.status!==200||response.redirected||Number(response.headers.get('content-length')??0)>1_000_000||!response.body)throw new Error('Source unavailable');
   const reader=response.body.getReader(),chunks:Uint8Array[]=[];let length=0;
   try{while(true){const part=await reader.read();if(part.done)break;length+=part.value.length;if(length>1_000_000)throw new Error('Source too large');chunks.push(part.value);}}finally{await reader.cancel().catch(()=>{});}
   body=Buffer.concat(chunks);if(!body.length)throw new Error('Empty source');
  }catch{throw new ApiError(502,'SOURCE_UNAVAILABLE','Official source could not be captured. Existing content was not changed.');}finally{clearTimeout(timer);}
  const check={id:randomUUID(),...value,url,sha256:createHash('sha256').update(body).digest('hex'),retrieved_at:now()};
  db.prepare('INSERT INTO campus_source_checks(id,target_kind,target_id,url,sha256,retrieved_at,body,actor_id) VALUES(?,?,?,?,?,?,?,?)').run(check.id,value.target_kind,value.target_id,url,check.sha256,check.retrieved_at,body.toString('base64'),actor);
  return check;
 }
 function requireCheck(id:string,kind:string,targetId:string){const row=db.prepare('SELECT id,target_kind,target_id,url,sha256,retrieved_at FROM campus_source_checks WHERE id=?').get(id) as Check|undefined;if(!row||row.target_kind!==kind||row.target_id!==targetId||row.retrieved_at<now()-86400000)throw new ApiError(409,'SOURCE_CHECK_REQUIRED','Capture this official source again before saving.');return row;}
 function audit(actor:string,kind:string,id:string,action:string,reason:string,before:unknown,after:unknown,check:string|null){db.prepare('INSERT INTO campus_maintenance_audit(target_kind,target_id,actor_id,action,reason,before_json,after_json,source_check_id,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(kind,id,actor,action,reason,JSON.stringify(before),JSON.stringify(after),check,now());}
 function editPlace(actor:string,id:string,input:unknown){const value=placeEditSchema.parse(input);return transaction(db,()=>{const before=directory.entry(id);if(before.version!==value.version)throw stale();const check=requireCheck(value.source_check_id,'place',id);if(check.url!==before.source.url)throw new ApiError(409,'SOURCE_CHANGED','The official source changed.');const {version,freshness,...payload}=before;const next={...payload,...value.fields,source:{...payload.source,url:check.url,sha256:check.sha256,retrieved_at:new Date(check.retrieved_at).toISOString()},review_due_at:new Date(check.retrieved_at+30*86400000).toISOString(),open_now:'unknown',availability:'unknown'};db.prepare('UPDATE campus_entries SET payload=?,version=version+1 WHERE id=?').run(JSON.stringify(next),id);const after=directory.entry(id);audit(actor,'place',id,'edit_place',value.reason,before,after,check.id);return after;});}
 function resolve(actor:string,id:string,input:unknown){const value=z.object({version:z.number().int().positive(),status:z.enum(['resolved','rejected']),resolution:z.string().trim().min(5).max(1000),source_check_id:z.string().uuid().nullable().default(null)}).strict().parse(input);return transaction(db,()=>{const before=db.prepare('SELECT * FROM campus_corrections WHERE id=?').get(id) as Correction|undefined;if(!before)throw new ApiError(404,'CORRECTION_NOT_FOUND','Correction not found.');if(before.version!==value.version||before.status!=='pending')throw stale();if(value.status==='resolved'||value.source_check_id)requireCheck(value.source_check_id??'',before.target_kind,before.target_id);db.prepare('UPDATE campus_corrections SET status=?,resolution=?,version=version+1,reviewed_at=?,reviewer_id=? WHERE id=?').run(value.status,value.resolution,now(),actor,id);const after=db.prepare('SELECT id,target_kind,target_id,message,status,resolution,created_at,version,reviewed_at FROM campus_corrections WHERE id=?').get(id);audit(actor,before.target_kind,before.target_id,'correction_'+value.status,value.resolution,{id:before.id,status:before.status,version:before.version},{id,status:value.status,version:before.version+1,resolution:value.resolution},value.source_check_id);return after;});}
 function history(input:unknown){const value=maintenanceTarget.parse(input);return db.prepare('SELECT id,action,reason,actor_id,before_json,after_json,source_check_id,created_at FROM campus_maintenance_audit WHERE target_kind=? AND target_id=? ORDER BY id DESC LIMIT 50').all(value.target_kind,value.target_id).map(row=>({...row,before:JSON.parse(String(row.before_json)),after:JSON.parse(String(row.after_json)),before_json:undefined,after_json:undefined}));}
 return {listCorrections,checkSource,editPlace,resolve,history,requireCheck,audit};
}
