import Link from 'next/link';
import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {publicActivity} from '../../../lib/public-activities';
import {localPageConfig,pageLanguage,eventTime,type PageQuery} from '../../../lib/page-config';
import {WebFailure} from '../../../lib/product-web';
type Props={params:Promise<{id:string}>;searchParams:PageQuery};
export const dynamic='force-dynamic';
export async function generateMetadata({params}:Props):Promise<Metadata>{try{const a=await publicActivity(await localPageConfig(),(await params).id);return {title:a.title,description:'Local development demo activity. Public preview only.',robots:{index:false,follow:false}};}catch{return {title:'Activity unavailable',description:'Public activity preview unavailable.',robots:{index:false,follow:false}};}}
export default async function ActivityShare({params,searchParams}:Props){const language=pageLanguage(await searchParams),zh=language==='zh';let a:Awaited<ReturnType<typeof publicActivity>>;try{a=await publicActivity(await localPageConfig(),(await params).id);}catch(e){if(e instanceof WebFailure&&e.status===404)notFound();return <section className="campus-shell campus-page"><h1>{zh?'暂时无法读取活动':'Activity unavailable'}</h1><p role="alert">{zh?'本地服务没有响应，请稍后刷新。':'The local service did not respond. Refresh to try again.'}</p><Link href={'/events?lang='+language}>{zh?'返回公开活动':'Back to activities'}</Link></section>;}
 return <section className="campus-shell campus-page campus-share" lang={zh?'zh-Hans':'en'}><Link className="campus-text-link" href={'/events?lang='+language}>{zh?'返回公开活动':'Back to activities'}</Link><p className="campus-status">{zh?'本地开发演示 · 公开活动预览':'Local development demo · Public preview'}</p><h1>{a.title}</h1><p className="campus-state">{a.status==='cancelled'?(zh?'活动已取消':'Activity cancelled'):a.ended?(zh?'活动已结束':'Activity ended'):a.started?(zh?'活动已开始':'Activity started'):a.status==='closed'?(zh?'报名已关闭':'Signups closed'):(zh?'开放报名':'Open for signup')}</p><dl className="campus-facts"><div><dt>{zh?'时间':'When'}</dt><dd>{eventTime(a.starts_at,language)} — {eventTime(a.ends_at,language)} HKT</dd></div><div><dt>{zh?'地点':'Where'}</dt><dd>{a.location}</dd></div><div><dt>{zh?'组织者':'Organizer'}</dt><dd>{a.organizer.display_name}</dd></div><div><dt>{zh?'名额':'Places'}</dt><dd>{a.counts.confirmed} / {a.capacity} {zh?'已确认，不含组织者':'confirmed, organizer excluded'} · {a.counts.waitlisted} {zh?'候补':'waitlisted'}</dd></div><div><dt>{zh?'语言':'Languages'}</dt><dd>{a.languages.map(l=>l==='en'?'English':l==='zh'?(zh?'普通话':'Mandarin'):(zh?'粤语':'Cantonese')).join(' / ')}</dd></div><div><dt>{zh?'相处方式':'Interaction'}</dt><dd>{a.interaction==='quiet'?(zh?'安静共处，无需主动聊天':'Quiet company, no need to chat'):a.interaction==='casual'?(zh?'随意交流':'Casual conversation'):(zh?'讨论／协作':'Active collaboration')}</dd></div><div><dt>{zh?'预计费用':'Expected cost'}</dt><dd>{a.cost_minor===0?(zh?'免费':'Free'):'HK$ '+(a.cost_minor/100).toFixed(2)} {zh?'（仅说明，不收款）':'(informational, no payment collected)'}</dd></div></dl>{a.description?<div className="campus-prose"><h2>{zh?'一起做什么':'What we will do'}</h2><p>{a.description}</p></div>:null}{a.requirements?<div className="campus-prose"><h2>{zh?'参与条件':'Requirements'}</h2><p>{a.requirements}</p></div>:null}<aside className="campus-status"><h2>{zh?'想参加？在 App 里查看最新状态':'Interested? Check the latest state in the app'}</h2><p>{zh?'在 iOS 开发版的“发现”中找到这场活动并报名。名额满后可候补，也可随时退出。网页预览不会代你报名或保存日程。':'Find this activity in Discover in the iOS development app. Join, waitlist when full, or withdraw at any time. This web preview does not join or save your calendar.'}</p><p>{zh?'可复制此页面链接分享。活动的可见范围仍由后端决定。':'Copy this page URL to share. The backend still controls visibility.'}</p></aside></section>;}
