'use client';
import {useAdminInput} from './admin-input-protection';
import {useEffect,useRef,useState} from 'react';
import type {Activity} from '../../../src/product/social/types';
type Entry=Activity&{moderation_state:string;organizer_restricted:boolean};
type Audit={id:number;action:string;reason:string;fields:string[];before_version:number;after_version:number;created_at:number};
type Draft={title:string;description:string;location:string;starts_at:string;ends_at:string;capacity:number;languages:('zh'|'en'|'yue')[];interaction:'quiet'|'casual'|'active';cost_minor:number;requirements:string;status:'open'|'closed'};
const localDate=(iso:string)=>new Date(Date.parse(iso)+8*3600000).toISOString().slice(0,16);
function draftOf(a:Entry):Draft{return {title:a.title,description:a.description,location:a.location,starts_at:localDate(a.starts_at),ends_at:localDate(a.ends_at),capacity:a.capacity,languages:[...a.languages],interaction:a.interaction,cost_minor:a.cost_minor,requirements:a.requirements,status:a.status==='closed'?'closed':'open'};}
export function ActivityMaintenance({language,request,onSessionExpired}:{language:'zh'|'en';request:<T>(path:string,body?:unknown)=>Promise<T>;onSessionExpired:()=>void}){
 const zh=language==='zh',t=(cn:string,en:string)=>zh?cn:en;
 const [items,setItems]=useState<Entry[]>([]),[cursor,setCursor]=useState<string|null>(null),[q,setQ]=useState(''),[status,setStatus]=useState('all');
 const [selected,setSelected]=useState<Entry|null>(null),[draft,setDraft]=useState<Draft|null>(null),[history,setHistory]=useState<Audit[]>([]),[reason,setReason]=useState(''),[action,setAction]=useState<'edit'|'cancel'>('edit');
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[review,setReview]=useState(false),[uncertain,setUncertain]=useState(false),[latest,setLatest]=useState<Entry|null>(null);
 const alive=useRef(true),lock=useRef(false),dialog=useRef<HTMLDialogElement>(null),keep=useRef<HTMLButtonElement>(null),previousFocus=useRef<HTMLElement|null>(null),detailHeading=useRef<HTMLHeadingElement>(null);
 const dirty=!!(selected&&draft&&(JSON.stringify(draft)!==JSON.stringify(draftOf(selected))||reason||action==='cancel'));
 useAdminInput('activities',dirty||uncertain,busy);
 const locked=!!selected&&(selected.status==='cancelled'||selected.moderation_state!=='visible'||selected.organizer_restricted);
 const differences=selected&&draft?Object.keys(draft).filter(k=>JSON.stringify(draft[k as keyof Draft])!==JSON.stringify(draftOf(selected)[k as keyof Draft])) as (keyof Draft)[]:[];
 const labels:Record<keyof Draft,string>={title:t('标题','Title'),description:t('活动说明','Description'),location:t('地点','Location'),starts_at:t('开始时间','Starts'),ends_at:t('结束时间','Ends'),capacity:t('人数上限','Capacity'),languages:t('语言','Languages'),interaction:t('互动方式','Interaction'),cost_minor:t('费用（港币分）','Cost (HKD cents)'),requirements:t('参与要求','Requirements'),status:t('报名状态','Registration')};
 const show=(v:unknown)=>Array.isArray(v)?v.join(' / '):String(v===null||v===undefined||v===''?'—':v);
 function failure(e:unknown,write=false){const f=e as {status?:number;code?:string};if(f.status===401||f.status===403&&f.code!=='CSRF_REQUIRED'){onSessionExpired();return;}if(write&&(f.status===409||!f.status||f.status>=500)){setUncertain(true);setReview(false);setError(t('结果尚未确认或活动已变化。草稿已保留；先读取当前记录，再决定下一步。','The result is uncertain or the activity changed. Your draft is retained. Read the current record before continuing.'));}else setError(f.status===400?t('请核对填写内容、时间和参与条件。草稿已保留。','Check the fields, times and participation conditions. Your draft is retained.'):f.code==='CSRF_REQUIRED'?t('会话校验已变化，请重新连接后操作。','Session protection changed. Reconnect before continuing.'):t('读取失败，请重试。','Could not load. Please retry.'));}
 async function run(job:()=>Promise<void>,write=false){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await job();}catch(e){if(alive.current)failure(e,write);}finally{lock.current=false;if(alive.current)setBusy(false);}}
 function adopt(a:Entry){setSelected(a);setDraft(draftOf(a));setReason('');setAction('edit');setReview(false);setUncertain(false);setLatest(null);}
 async function load(next?:string){await run(async()=>{const page=await request<{items:Entry[];next_cursor:string|null}>('/admin/activities?'+new URLSearchParams({q,status,...(next?{cursor:next}:{})}));if(alive.current){setItems(old=>next?[...old,...page.items.filter(x=>!old.some(y=>y.id===x.id))]:page.items);setCursor(page.next_cursor);}});}
 async function select(a:Entry){await run(async()=>{const current=await request<Entry>('/admin/activities/'+a.id);if(!alive.current)return;adopt(current);setHistory([]);try{const audit=await request<Audit[]>('/admin/activities/'+a.id+'/history');if(alive.current)setHistory(audit);}catch{if(alive.current)setNotice(t('活动已读取，维护记录暂时不可用。','Activity loaded; maintenance history is temporarily unavailable.'));}});}
 useEffect(()=>{alive.current=true;void load();return()=>{alive.current=false;};},[]); // Initial read only; filters apply on explicit search.
 useEffect(()=>{if(selected){detailHeading.current?.focus({preventScroll:true});detailHeading.current?.scrollIntoView({block:'start'});}},[selected?.id]);
 useEffect(()=>{if(dirty)setNotice('');},[dirty,draft,reason,action]);
 function field<K extends keyof Draft>(key:K,value:Draft[K]){setDraft(old=>old?{...old,[key]:value}:old);setReview(false);}
 function askDiscard(){previousFocus.current=document.activeElement as HTMLElement;dialog.current?.showModal();keep.current?.focus();}
 function closeDiscard(){dialog.current?.close();previousFocus.current?.focus();}
 async function save(){if(!selected||!draft||!review||uncertain)return;const snapshot=selected;const changes:Record<string,unknown>={};for(const key of differences)changes[key]=key==='starts_at'||key==='ends_at'?new Date(draft[key]+':00+08:00').toISOString():draft[key];await run(async()=>{const saved=await request<Entry>('/admin/activities/'+snapshot.id+'/maintain',{version:snapshot.version,reason,action,...(action==='edit'?{changes}:{})});if(!alive.current)return;adopt(saved);setItems(old=>old.map(x=>x.id===saved.id?saved:x));setHistory([]);setNotice(t('已保存。参与者消息与已选择保存的日程已同步。','Saved. Participant messages and opted-in calendars are updated.'));try{const audit=await request<Audit[]>('/admin/activities/'+saved.id+'/history');if(alive.current)setHistory(audit);}catch{if(alive.current)setNotice(t('保存成功，维护记录暂时无法刷新。请勿重复提交。','Saved, but history could not refresh. Do not submit again.'));}},true);}
 return <section className="activity-admin" aria-label={t('活动维护','Activity maintenance')}>
  <div className="activity-admin-heading"><div><p className="campus-note">{t('活动与学习招募','Activities & study groups')}</p><h2>{t('让每一次变化，都有交代。','Keep everyone in the loop.')}</h2><p>{t('维护活动安排；改期会更新消息和已保存日程，取消会清除相关提醒。所有记录均为本地测试内容。','Maintain schedules. Changes update messages and saved calendars; cancellation clears related reminders. All records are local test content.')}</p></div></div>
  <form className="campus-actions" onSubmit={e=>{e.preventDefault();void load();}}><label>{t('搜索标题或地点','Search title or location')}<input value={q} maxLength={120} disabled={busy||dirty||uncertain} onChange={e=>setQ(e.target.value)} placeholder={t('例如：安静自习','e.g. Quiet study')}/></label><label>{t('活动状态','Activity status')}<select value={status} disabled={busy||dirty||uncertain} onChange={e=>setStatus(e.target.value)}><option value="all">{t('全部','All')}</option><option value="open">{t('可报名','Open')}</option><option value="closed">{t('停止报名','Closed')}</option><option value="cancelled">{t('已取消','Cancelled')}</option></select></label><button className="campus-button campus-secondary" disabled={busy||dirty||uncertain}>{t('搜索 / 刷新','Search / refresh')}</button></form>
  {dirty?<p className="campus-note">{t('有未保存内容。切换后台栏目会保留草稿；切换活动前请保存或放弃修改。','Unsaved changes. Switching admin sections keeps your draft; save or discard before selecting another activity.')}</p>:null}
  {error?<p role="alert" className="campus-error">{error}</p>:null}{notice?<p role="status" className="campus-status">{notice}</p>:null}{busy?<p role="status">{t('正在处理…','Working…')}</p>:null}
  <div className="campus-review-grid"><div className="activity-admin-list">{!items.length&&!busy?<p className="campus-empty">{t('没有符合条件的活动。调整搜索条件后再试。','No matching activities. Try another search.')}</p>:null}{items.map(a=><button key={a.id} className="activity-admin-item" aria-pressed={selected?.id===a.id} disabled={busy||dirty||uncertain} onClick={()=>void select(a)}><span className="campus-note">{a.kind==='study'?t('学习招募','Study group'):t('活动','Activity')} · {a.status} · DEMO</span><strong>{a.title}</strong><span>{new Date(a.starts_at).toLocaleString(zh?'zh-HK':'en-HK',{timeZone:'Asia/Hong_Kong'})} · {a.location}</span><span className="campus-note">{a.counts.confirmed}/{a.capacity} · {a.counts.waitlisted} {t('候补','waiting')}</span></button>)}{cursor?<button className="campus-button campus-secondary" disabled={busy||dirty||uncertain} onClick={()=>void load(cursor)}>{t('加载更多','Load more')}</button>:null}</div>
  {selected&&draft?<section className="campus-review-detail"><h3 ref={detailHeading} tabIndex={-1} className="activity-admin-detail-title">{selected.title}</h3><p className="campus-note">{t('组织者','Organizer')}: {selected.organizer.display_name||selected.organizer.id} · {selected.visibility} · v{selected.version}<br/>{t('状态','Status')}: {selected.status} / {selected.moderation_state}</p>
   {locked?<p className="campus-status">{t('此活动已取消或受限，仅供查阅，不能在这里恢复。','This activity is cancelled or restricted. Read only; it cannot be restored here.')}</p>:null}
   {locked?<dl className="activity-admin-diff">{(['location','starts_at','ends_at','description','requirements'] as const).map(k=><div key={k}><dt>{labels[k]}</dt><dd>{show(draft[k])}</dd></div>)}</dl>:<form onSubmit={e=>{e.preventDefault();setReview(true);}}><fieldset disabled={busy||locked||review||uncertain} className="activity-admin-fields">
    <label>{t('维护方式','Action')}<select value={action} onChange={e=>setAction(e.target.value as 'edit'|'cancel')}><option value="edit">{t('修改活动安排','Edit activity')}</option><option value="cancel">{t('取消活动（不可恢复）','Cancel activity (final)')}</option></select></label>
    {action==='edit'?<>{(['title','location'] as const).map(k=><label key={k}>{labels[k]}<input required maxLength={k==='title'?120:300} value={draft[k]} onChange={e=>field(k,e.target.value)}/></label>)}<div className="activity-admin-pair">{(['starts_at','ends_at'] as const).map(k=><label key={k}>{labels[k]} · HKT<input type="datetime-local" required value={draft[k]} onInput={e=>field(k,e.currentTarget.value)} onChange={e=>field(k,e.target.value)}/></label>)}</div><div className="activity-admin-pair"><label>{labels.capacity}<input type="number" required min={Math.max(1,selected.counts.confirmed)} max={50} value={draft.capacity} onChange={e=>field('capacity',Number(e.target.value))}/></label><label>{labels.cost_minor}<input type="number" required min={0} max={100000} value={draft.cost_minor} onChange={e=>field('cost_minor',Number(e.target.value))}/></label></div><label>{labels.status}<select value={draft.status} onChange={e=>field('status',e.target.value as 'open'|'closed')}><option value="open">{t('开放报名','Open')}</option><option value="closed">{t('停止新增报名','Close registration')}</option></select></label><label>{labels.interaction}<select value={draft.interaction} onChange={e=>field('interaction',e.target.value as Draft['interaction'])}><option value="quiet">{t('安静相处','Quiet')}</option><option value="casual">{t('轻松交流','Casual')}</option><option value="active">{t('积极互动','Active')}</option></select></label><div><span>{labels.languages}</span><div className="campus-actions">{(['zh','en','yue'] as const).map(l=><label key={l} className="activity-admin-check"><input type="checkbox" checked={draft.languages.includes(l)} onChange={e=>field('languages',e.target.checked?[...draft.languages,l]:draft.languages.filter(x=>x!==l))}/>{l==='zh'?t('普通话','Mandarin'):l==='en'?'English':t('粤语','Cantonese')}</label>)}</div></div>{(['description','requirements'] as const).map(k=><label key={k}>{labels[k]}<textarea rows={3} maxLength={k==='description'?5000:2000} value={draft[k]} onChange={e=>field(k,e.target.value)}/></label>)}</>:<p className="campus-error">{t('已报名及候补将全部取消，保存的活动日程与提醒将移除，组织者与相关参与者会收到站内通知。','Confirmed and waiting participants will be cancelled. Saved event calendars and reminders will be removed, and the organizer and relevant participants will receive in-app notices.')}</p>}
    <label>{t('维护原因（管理员可见，至少 5 字）','Reason (administrators only, 5+ characters)')}<textarea required minLength={5} maxLength={1000} rows={2} value={reason} onChange={e=>setReason(e.target.value)}/></label>
   </fieldset>
   {review?<div className="campus-status" role="group" aria-label={t('确认活动变化','Confirm activity changes')}><h4>{action==='cancel'?t('确认取消此活动？','Cancel this activity?'):t('检查本次变化','Review these changes')}</h4>{action==='edit'?<dl className="activity-admin-diff">{differences.map(k=><div key={k}><dt>{labels[k]}</dt><dd>{show(draftOf(selected)[k])} → <strong>{show(draft[k])}</strong></dd></div>)}</dl>:<p>{selected.title} · {t('取消后不可恢复','Cancellation is final')}</p>}<p>{t('原因','Reason')}: {reason}</p><div className="campus-actions"><button type="button" className="campus-button" disabled={busy||uncertain} onClick={()=>void save()}>{action==='cancel'?t('确认取消活动','Confirm cancellation'):t('确认保存变化','Confirm changes')}</button><button type="button" className="campus-button campus-secondary" disabled={busy} onClick={()=>setReview(false)}>{t('返回修改','Back to edit')}</button></div></div>:!locked&&!uncertain?<button className="campus-button" disabled={busy||reason.trim().length<5||action==='edit'&&(!differences.length||!draft.languages.length)}>{t('检查变化','Review changes')}</button>:null}
   </form>}
   {uncertain?<div className="campus-status"><button className="campus-button campus-secondary" disabled={busy} onClick={()=>void run(async()=>{const current=await request<Entry>('/admin/activities/'+selected.id);if(alive.current)setLatest(current);})}>{t('读取当前记录（保留草稿）','Read current record (keep draft)')}</button>{latest?<><p>{t('服务器当前记录','Current server record')}: v{latest.version} · {latest.status}</p><dl className="activity-admin-diff">{Object.keys(draft).map(k=><div key={k}><dt>{labels[k as keyof Draft]}</dt><dd>{show(draftOf(latest)[k as keyof Draft])}</dd></div>)}</dl><p>{t('上方仍保留你的草稿。核对后可使用当前记录重新编辑。','Your draft remains above. After checking, use the current record to start a new edit.')}</p></>:null}</div>:null}
   {(dirty||uncertain)&&!busy?<button className="campus-button campus-secondary" onClick={askDiscard}>{latest?t('放弃草稿，使用当前记录','Discard draft, use current record'):t('放弃未保存修改','Discard unsaved changes')}</button>:null}
   <details className="activity-admin-history"><summary>{t('最近维护记录','Recent maintenance history')} · {history.length}</summary>{history.map(h=><article key={h.id}><p>{h.action} · v{h.before_version} → v{h.after_version} · {new Date(h.created_at).toLocaleString(zh?'zh-HK':'en-HK',{timeZone:'Asia/Hong_Kong'})}</p><p>{h.reason}</p><p className="campus-note">{h.fields.join(', ')}</p></article>)}</details>
  </section>:<aside className="campus-review-detail"><h3>{t('选择一场活动','Select an activity')}</h3><p>{t('先核对当前安排，再检查具体变化。系统会保留维护原因和版本记录。','Check the current schedule, then review specific changes. The reason and version history are recorded.')}</p></aside>}</div>
  <dialog ref={dialog} aria-labelledby="activity-discard-title" className="campus-discard-dialog" onCancel={()=>previousFocus.current?.focus()}><h3 id="activity-discard-title">{t('放弃这份草稿？','Discard this draft?')}</h3><p>{t('未保存的文字将被清除。服务器上的活动不会因此改变。','Unsaved text will be cleared. This does not change the activity on the server.')}</p><div className="campus-actions"><button ref={keep} className="campus-button" onClick={closeDiscard}>{t('继续编辑','Keep editing')}</button><button className="campus-button campus-secondary" onClick={()=>{if(selected)adopt(latest??selected);closeDiscard();}}>{t('确认放弃','Discard draft')}</button></div></dialog>
 </section>;
}
