'use client';
import {useRef,useState} from 'react';
import {Glyph} from './campus-preview';
export function CampusDayExperience({language}:{language:'zh'|'en'}){
 const zh=language==='zh',t=(z:string,e:string)=>zh?z:e;
 const [mood,setMood]=useState(0),[saved,setSaved]=useState<number|null>(null); const dialog=useRef<HTMLDialogElement>(null);
 const plans=[{title:t('各学各的，也算一起。','Your own work. Good company.'),kind:t('安静自习','Quiet study'),time:'15:00—16:30',location:t('图书馆 · 示例地点','Library · Example location'),note:t('带上电脑，安静坐一会儿。无需破冰，也不用一直说话。','Bring a laptop and settle in. No icebreakers. No pressure to keep talking.'),people:t('3 人小组 · 普通话 / 英语','3 people · Mandarin / English'),icon:'book' as const},{title:t('走慢一点，聊到哪算哪。','A slower walk. An easy chat.'),kind:t('海边散步','Seafront walk'),time:'18:30—19:15',location:t('清水湾 · 示例集合点','Clear Water Bay · Example meeting point'),note:t('一天结束后出去走走。可以聊，也可以只是一起看海。','Step outside after a long day. Talk a little, or just enjoy the sea.'),people:t('4 人小组 · 轻松聊天','4 people · Casual conversation'),icon:'people' as const},{title:t('一个小问题，就能开个头。','A small question opens a door.'),kind:t('学习组队','Study group'),time:'16:30—17:30',location:t('学习空间 · 示例地点','Study space · Example location'),note:t('各自带一个卡住的问题，一起理清思路。第一次参加也欢迎。','Bring a problem you are stuck on and work through it together. First-timers welcome.'),people:t('3 人小组 · 学习交流','3 people · Study discussion'),icon:'today' as const}]; const plan=plans[mood];
 return <div className="day-experience"><div className="day-choice"><p className="campus-eyebrow">{t('点一下，试试你的下午','TRY YOUR AFTERNOON')}</p><h3>{t('今天的你，','Today, you feel like…')}<br/>{t('想怎样和人相处？','')}</h3><p>{t('先选舒服的相处方式，再看一个具体的小计划。','Choose a comfortable way to spend time with people, then explore a small plan.')}</p><div className="mood-options" aria-label={t('选择相处方式','Choose an interaction style')}>{[t('安静待着','Quiet company'),t('轻松聊聊','Easy conversation'),t('一起学点什么','Learn together')].map((v,i)=><button key={v} aria-pressed={mood===i} onClick={()=>setMood(i)}><span>0{i+1}</span>{v}<Glyph name="chevron" size={16}/></button>)}</div><p className="story-caption">{t('交互概念演示 · 不使用你的真实课表，不产生真实报名','Interactive concept · No access to your timetable or real registration')}</p></div><div className="day-live" key={mood}><div className="day-live-top"><span>MON · 05</span><span>{t('示例下午','Example afternoon')}</span></div><div className="day-class"><span>13:00</span><div><strong>{t('课程结束','Class finishes')}</strong><small>{t('个人课表仅自己可见','Your timetable stays private')}</small></div><Glyph name="check" size={18}/></div><div className="day-connector"><span/>{t('空出一段时间，留给自己','A little time opens up')}</div><article className="day-plan"><span className="day-plan-kind"><Glyph name={plan.icon} size={18}/>{plan.kind}</span><h4>{plan.title}</h4><p>{plan.note}</p><dl><div><dt>{t('时间','When')}</dt><dd>{plan.time}</dd></div><div><dt>{t('地点','Where')}</dt><dd>{plan.location}</dd></div><div><dt>{t('氛围','Vibe')}</dt><dd>{plan.people}</dd></div></dl><button className="campus-button" onClick={()=>dialog.current?.showModal()}>{saved===mood?t('查看已选安排','View chosen plan'):t('试试加入这份安排','Try adding this plan')}</button></article><div className={'day-result'+(saved===mood?' is-saved':'')} role="status"><Glyph name={saved===mood?'check':'lock'} size={17}/><span>{saved===mood?t('已加入示例日程。你可以随时撤销。','Added to the example calendar. Undo anytime.'):t('先看清安排，再决定要不要加入。','See the plan before deciding to join.')}</span>{saved===mood?<button onClick={()=>setSaved(null)}>{t('撤销','Undo')}</button>:null}</div></div><dialog ref={dialog} className="plan-confirm" onClick={e=>{if(e.target===e.currentTarget)dialog.current?.close();}} aria-labelledby="plan-confirm-title"><form method="dialog"><span className="campus-eyebrow">{t('体验演示','EXPERIENCE DEMO')}</span><h3 id="plan-confirm-title">{t('把这段时间留给自己？','Make room for this plan?')}</h3><p>{plan.title}</p><div className="confirm-facts"><strong>{plan.time}</strong><span>{plan.location}</span><span>{plan.people}</span></div><p className="story-caption">{t('这里只更新网页里的示例日程。没有真实报名，不会读取或修改你的日历。','This only changes the example calendar on this page. No registration and no access to your calendar.')}</p><div className="campus-actions"><button className="campus-button" onClick={()=>setSaved(mood)}>{t('确认示例安排','Confirm example plan')}</button><button className="campus-text-link" value="cancel">{t('再看看','Keep looking')}</button></div></form></dialog></div>;
}
