'use client';
import {useAdminInput} from './admin-input-protection';
import {useCallback,useEffect,useId,useRef,useState} from 'react';
type Pair={zh:string;en:string};
type Fields={name:Pair;location:Pair;description:Pair;published_hours:Pair;map_url:string|null;action_url:string};
type Place=Fields&{id:string;version:number;freshness:string;review_due_at:string;source:{url:string;retrieved_at:string;sha256:string}};
type Correction={id:string;target_kind:'place'|'shuttle';target_id:string;message:string;status:string;resolution:string;version:number};
type Target={target_kind:'place'|'shuttle';target_id:string};
type Check=Target&{id:string;url:string;sha256:string;retrieved_at:number};
type History={id:number;action:string;reason:string;created_at:number;before:unknown;after:unknown};
export function CampusMaintenance({language,request,onSessionExpired}:{language:'zh'|'en';request:<T>(path:string,body?:unknown)=>Promise<T>;onSessionExpired:()=>void}){
 const zh=language==='zh',t=(cn:string,en:string)=>zh?cn:en;
 const [places,setPlaces]=useState<Place[]>([]),[corrections,setCorrections]=useState<Correction[]>([]),[status,setStatus]=useState('pending'),[cursor,setCursor]=useState<string|null>(null);
 const [selected,setSelected]=useState<Target|null>(null),[correction,setCorrection]=useState<Correction|null>(null),[fields,setFields]=useState<Fields|null>(null),[check,setCheck]=useState<Check|null>(null),[history,setHistory]=useState<History[]>([]);
 const [reason,setReason]=useState(''),[resolution,setResolution]=useState(''),[decision,setDecision]=useState('resolved'),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
 const lock=useRef(false),alive=useRef(true),epoch=useRef(0),detailHeading=useRef<HTMLHeadingElement>(null);
 const initialFields=useRef('');
 const [pendingLeave,setPendingLeave]=useState<(()=>void)|null>(null);
 const discardDialog=useRef<HTMLDialogElement>(null),discardOpener=useRef<HTMLElement|null>(null),discardTitle=useId();
 useEffect(()=>{if(pendingLeave&&!discardDialog.current?.open){discardOpener.current=document.activeElement as HTMLElement;discardDialog.current?.showModal();}},[pendingLeave]);
 const current=selected?.target_kind==='place'?places.find(p=>p.id===selected.target_id):null;
 const load=useCallback(async(next?:string)=>{
  const generation=++epoch.current;setBusy(true);setError('');
  try{const [p,q]=await Promise.all([request<Place[]>('/admin/campus/places'),request<{items:Correction[];next_cursor:string|null}>('/admin/campus/corrections?status='+status+(next?'&cursor='+next:''))]);if(!alive.current||generation!==epoch.current)return;setPlaces(p);setCorrections(old=>next?[...old,...q.items.filter(x=>!old.some(y=>y.id===x.id))]:q.items);setCursor(q.next_cursor);if(!next){initialFields.current='';setReason('');setResolution('');setReviewed(false);setNotice('');setSelected(null);setCorrection(null);setFields(null);setCheck(null);setHistory([]);}}
  catch(e){if(alive.current&&generation===epoch.current){setError(zh?'维护数据读取失败，请重新加载。':'Could not load maintenance data. Retry.');if([401,403].includes((e as {status:number}).status))onSessionExpired();}}
  finally{if(alive.current&&generation===epoch.current)setBusy(false);}
 },[request,status,zh,onSessionExpired]);
 useEffect(()=>{alive.current=true;void load();return()=>{alive.current=false;epoch.current++;};},[load]);
 function hasDraft(){return (fields!==null&&JSON.stringify(fields)!==initialFields.current)||reason.trim().length>0||(correction?.status==='pending'&&resolution.trim().length>0);}
 useAdminInput('campus',!!hasDraft(),busy);
 function leave(action:()=>void){if(hasDraft())setPendingLeave(()=>action);else action();}
 function closeDiscard(proceed:boolean){const action=pendingLeave;discardDialog.current?.close();setPendingLeave(null);if(proceed)action?.();else discardOpener.current?.focus({preventScroll:true});}
 useEffect(()=>{if(selected){detailHeading.current?.scrollIntoView({block:'start',behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});detailHeading.current?.focus({preventScroll:true});}},[selected?.target_kind,selected?.target_id,correction?.id]);
 function choose(target:Target,c?:Correction){leave(()=>select(target,c));}
 function select(target:Target,c?:Correction){setDecision('resolved');setSelected(target);setCorrection(c??null);setCheck(null);setHistory([]);setReason('');setResolution('');setReviewed(false);setError('');setNotice('');const p=places.find(p=>p.id===target.target_id);const nextFields=target.target_kind==='place'&&p?{name:{...p.name},location:{...p.location},description:{...p.description},published_hours:{...p.published_hours},map_url:p.map_url,action_url:p.action_url}:null;setFields(nextFields);initialFields.current=JSON.stringify(nextFields);}
 async function run(action:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await action();}catch(e){if(alive.current){const failure=e as {status:number;code:string};if([401,403].includes(failure.status)&&failure.code!=='CSRF_REQUIRED')onSessionExpired();setError(failure.code==='SOURCE_UNAVAILABLE'?t('官方来源未能读取，公开资料没有改动。请稍后重试。','Official source unavailable. Public content is unchanged. Retry later.'):failure.status===409?t('记录或来源核对已过期，请刷新后重新核对；不要重复提交旧版本。','Record or source check changed. Refresh and review before submitting again.'):t('未能确认结果，请刷新资料核对后再操作。','Result unconfirmed. Refresh the record before retrying.'));}}finally{lock.current=false;if(alive.current)setBusy(false);}}
 const pairField=(key:'name'|'location'|'description'|'published_hours',label:string)=><fieldset className="campus-maintenance-pair"><legend>{label}</legend>{(['zh','en'] as const).map(lang=><label key={lang}>{lang==='zh'?'中文':'English'}<textarea rows={key==='description'?3:2} maxLength={2000} required value={fields![key][lang]} disabled={busy} onChange={e=>{const value=e.target.value;setFields(old=>old?{...old,[key]:{...old[key],[lang]:value}}:old);setReviewed(false);}}/></label>)}</fieldset>;
 return <section aria-label={t('校园资料维护','Campus maintenance')}>
 <h2>{t('校园资料与纠错','Campus information & corrections')}</h2><p>{t('先核对官方来源，再保存公开资料。抓取成功不代表内容已更新；学生反馈不会自动修改资料。','Capture and review the official source before saving. A successful capture does not publish an update. Student feedback never edits content automatically.')}</p>
 {error?<p className="campus-error" role="alert">{error}</p>:null}{notice?<p className="campus-status" role="status">{notice}</p>:null}
 <div className="campus-actions"><label>{t('纠错状态','Correction status')}<select disabled={busy} value={status} onChange={e=>{const value=e.target.value;leave(()=>setStatus(value));}}>{['pending','resolved','rejected'].map((v,i)=><option key={v} value={v}>{[t('待核对','Pending'),t('已处理','Resolved'),t('未采纳','Rejected')][i]}</option>)}</select></label><button className="campus-button campus-secondary" disabled={busy} onClick={()=>leave(()=>void load())}>{busy?t('处理中…','Working…'):t('刷新维护资料','Refresh maintenance data')}</button></div>
 <div className="campus-review-grid"><div><h3>{t('纠错队列','Correction queue')}</h3>{!busy&&!corrections.length?<p className="campus-empty">{t('此队列为空。','This queue is empty.')}</p>:null}{corrections.map(c=><article className="campus-report" key={c.id}><h3>{c.target_id}</h3><p>{c.message}</p><p className="campus-note">{c.status} · v{c.version}</p><button className="campus-button campus-secondary" disabled={busy} onClick={()=>choose({target_kind:c.target_kind,target_id:c.target_id},c)}>{t('核对这条纠错','Review correction')}</button></article>)}{cursor?<button className="campus-button campus-secondary" disabled={busy} onClick={()=>void load(cursor)}>{t('加载更多','Load more')}</button>:null}<h3>{t('地点资料','Place directory')}</h3>{places.map(p=><article className="campus-report" key={p.id}><h3>{p.name[language]}</h3><p className="campus-note">v{p.version} · {p.freshness==='stale'?t('需重新核对','Review overdue'):t('已核对快照','Reviewed snapshot')}</p><button className="campus-button campus-secondary" disabled={busy} onClick={()=>choose({target_kind:'place',target_id:p.id})}>{t('编辑','Edit')} {p.name[language]}</button></article>)}</div>
 <div className="campus-review-detail">{selected?<><h3 ref={detailHeading} tabIndex={-1} className="campus-maintenance-heading">{current?.name[language]??selected.target_id}</h3>{current?<p className="campus-note">{t('来源上次抓取','Source captured')}: {current.source.retrieved_at}<br/>{t('应复核日期','Review due')}: {current.review_due_at}</p>:<p>{t('此处核对校巴来源并处理反馈。班次和假期表请在“校巴时刻与假期”栏目修改；仅核对来源不会改变班次。','Review shuttle sources and feedback here. Edit schedules in Shuttle & holidays; a source check alone does not change departures.')}</p>}
 <button className="campus-button" disabled={busy} onClick={()=>void run(async()=>{const captured=await request<Check>('/admin/campus/source-checks',selected);if(alive.current){setCheck(captured);setReviewed(false);setNotice(t('来源已抓取。请阅读官方页面并核对修改内容。','Source captured. Read the official page and review your changes.'));}})}>{t('抓取并核对官方来源','Capture official source')}</button>
 {check?<div className="campus-status"><a href={check.url} target="_blank" rel="noreferrer">{t('打开官方来源','Open official source')} ↗</a><p>{new Date(check.retrieved_at).toISOString()}</p><details><summary>{t('来源证据摘要','Source evidence')}</summary><code className="campus-hash">SHA-256 {check.sha256}</code></details></div>:null}
 {current&&fields?<form onSubmit={e=>{e.preventDefault();if(!check||!reviewed)return;void run(async()=>{const saved=await request<Place>('/admin/campus/places/'+current.id,{version:current.version,source_check_id:check.id,reason,fields});if(alive.current){setPlaces(old=>old.map(p=>p.id===saved.id?saved:p));initialFields.current=JSON.stringify(fields);setHistory([]);setReviewed(false);setReason('');setNotice(t('公开地点资料已保存。纠错仍需在下方单独记录处理结果。','Public place updated. Record the correction decision separately below.'));}});}}>{pairField('name',t('名称','Name'))}{pairField('location',t('位置','Location'))}{pairField('description',t('说明','Description'))}{pairField('published_hours',t('公布开放时间','Published hours'))}{(['map_url','action_url'] as const).map(key=><label key={key}>{key==='map_url'?t('官方地图链接（选填）','Official map URL (optional)'):t('官方服务链接','Official service URL')}<input type="url" required={key==='action_url'} value={fields[key]??''} disabled={busy} onChange={e=>{const value=e.target.value;setFields(old=>old?{...old,[key]:key==='map_url'?value||null:value}:old);setReviewed(false);}}/></label>)}<label>{t('本次修改说明','Reason for this edit')}<textarea required minLength={5} maxLength={1000} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label><label className="campus-maintenance-confirm"><input type="checkbox" checked={reviewed} disabled={busy||!check} onChange={e=>setReviewed(e.target.checked)}/>{t('我已核对官方来源和中英文内容；这不代表实时开放或余位。','I reviewed the source and both languages. This is not live opening or availability data.')}</label><button className="campus-button" disabled={busy||!check||!reviewed||reason.trim().length<5}>{t('保存已核对资料','Save reviewed information')}</button></form>:null}
 {correction?<section><h3>{t('反馈处理结果','Correction decision')}</h3><p>{correction.message}</p>{correction.status==='pending'?<form onSubmit={e=>{e.preventDefault();void run(async()=>{const saved=await request<Correction>('/admin/campus/corrections/'+correction.id+'/resolve',{version:correction.version,status:decision,resolution,source_check_id:decision==='resolved'?check?.id??null:null});if(alive.current){setHistory([]);setCorrection(saved);setCorrections(old=>old.filter(c=>c.id!==saved.id));setNotice(t('处理结果已保存，提交者刷新个人记录后可查看。','Decision saved. The submitter can refresh their correction history.'));}});}}><label>{t('决定','Decision')}<select value={decision} disabled={busy} onChange={e=>setDecision(e.target.value)}><option value="resolved">{t('已核对并处理','Reviewed and resolved')}</option><option value="rejected">{t('不采纳','Reject')}</option></select></label><label>{t('给提交者的说明','Explanation to the submitter')}<textarea required minLength={5} maxLength={1000} disabled={busy} value={resolution} onChange={e=>setResolution(e.target.value)}/></label><button className="campus-button" disabled={busy||resolution.trim().length<5||(decision==='resolved'&&!check)}>{t('保存处理结果','Save decision')}</button></form>:<p>{correction.resolution}</p>}</section>:null}
 <button className="campus-button campus-secondary" disabled={busy} onClick={()=>void run(async()=>{const rows=await request<History[]>('/admin/campus/history?'+new URLSearchParams(selected));if(alive.current)setHistory(rows);})}>{t('查看修改记录','View history')}</button>{history.map(row=><details key={row.id}><summary>{row.action} · {new Date(row.created_at).toISOString()}</summary><p>{row.reason}</p><pre className="campus-history">{JSON.stringify({before:row.before,after:row.after},null,2)}</pre></details>)}</>:<p>{t('选择一条纠错或地点，开始核对。','Select a correction or place to review.')}</p>}</div></div>
 <dialog ref={discardDialog} className="campus-discard-dialog" aria-labelledby={discardTitle} onCancel={event=>{event.preventDefault();closeDiscard(false);}}>
 <h2 id={discardTitle}>{t('保留当前修改？','Keep your current changes?')}</h2><p>{t('离开这条记录会放弃尚未保存的输入，已保存的资料不会受影响。','Leaving this record discards unsaved input. Saved information stays unchanged.')}</p>
 <div className="campus-actions"><button autoFocus className="campus-button" onClick={()=>closeDiscard(false)}>{t('继续编辑','Keep editing')}</button><button className="campus-button campus-secondary" onClick={()=>closeDiscard(true)}>{t('放弃修改并继续','Discard and continue')}</button></div>
 </dialog>
 </section>;
}
