'use client';
import {useAdminInput} from './admin-input-protection';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {ShuttleCatalog,ShuttleDepartures,ShuttleRoute} from '../../../src/product/campus/shuttle';
type Snapshot={revision:number;catalog:ShuttleCatalog};
type Fields=Omit<ShuttleRoute,'id'|'source'|'refresh_due_at'>;
type Check={id:string;url:string;sha256:string;retrieved_at:number};
type History={id:number;action:string;reason:string;created_at:number;before:unknown;after:unknown};
const fieldsOf=(r:ShuttleRoute):Fields=>{const {id,source,refresh_due_at,...fields}=r;return structuredClone(fields);};
export function ShuttleMaintenance({language,request,onSessionExpired}:{language:'zh'|'en';request:<T>(path:string,body?:unknown)=>Promise<T>;onSessionExpired:()=>void}){
 const zh=language==='zh',t=(cn:string,en:string)=>zh?cn:en;
 const [snapshot,setSnapshot]=useState<Snapshot|null>(null),[mode,setMode]=useState<'route'|'holidays'>('route'),[routeId,setRouteId]=useState(''),[fields,setFields]=useState<Fields|null>(null);
 const [times,setTimes]=useState(''),[years,setYears]=useState(''),[holidays,setHolidays]=useState(''),[reason,setReason]=useState(''),[check,setCheck]=useState<Check|null>(null);
 const [preview,setPreview]=useState<ShuttleDepartures|null>(null),[reviewed,setReviewed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[history,setHistory]=useState<History[]>([]);
 const [at,setAt]=useState(()=>new Date(Date.now()+8*3600000).toISOString().slice(0,10)+'T08:00');
 const lock=useRef(false),alive=useRef(true),dialog=useRef<HTMLDialogElement>(null),opener=useRef<HTMLElement|null>(null);
 const original=snapshot?.catalog.routes.find(r=>r.id===routeId);
 const dirty=!!snapshot&&(reason.length>0||(mode==='route'?!!fields&&(JSON.stringify(fields)!==JSON.stringify(original?fieldsOf(original):null)||times!==(original?.departures.join('\n')??'')):years!==snapshot.catalog.holiday_years.join(', ')||holidays!==snapshot.catalog.holidays.map(h=>h.date+' | '+h.name).join('\n')));
 useAdminInput('shuttle',dirty,busy);
 function reset(data:Snapshot,id=routeId){const route=data.catalog.routes.find(r=>r.id===id)??data.catalog.routes[0];setSnapshot(data);setRouteId(route.id);setFields(fieldsOf(route));setTimes(route.departures.join('\n'));setYears(data.catalog.holiday_years.join(', '));setHolidays(data.catalog.holidays.map(h=>h.date+' | '+h.name).join('\n'));setReason('');setCheck(null);setPreview(null);setReviewed(false);setHistory([]);}
 const load=useCallback(async()=>{const data=await request<Snapshot>('/admin/campus/shuttle');return data;},[request]);
 async function run(job:()=>Promise<void>){if(lock.current)return;lock.current=true;setBusy(true);setError('');setNotice('');try{await job();}catch(e){if(alive.current){const failure=e as {status?:number;code?:string;message?:string};if([401,403].includes(failure.status??0)&&failure.code!=='CSRF_REQUIRED')onSessionExpired();setError(failure.status===409?t('资料或来源版本已变化。草稿保留；请记录修改，重新加载并核对后再保存。','The catalog or source changed. Draft retained. Keep a copy, reload and review before saving.'):failure.status===400?t('内容未通过校验：时间须按顺序且不重复，日期和假期年份必须对应。','Validation failed: times must be unique and ordered; dates and holiday coverage must match.'):failure.code==='SOURCE_UNAVAILABLE'?t('官方来源暂时无法读取，公开资料未改变。','Official source unavailable. Public data unchanged.'):t('未能确认结果。输入已保留；请重新读取实际版本，勿重复提交。','Result unconfirmed. Input retained. Read the actual version before retrying.'));}}finally{lock.current=false;if(alive.current)setBusy(false);}}
 useEffect(()=>{alive.current=true;void run(async()=>{const data=await load();if(alive.current)reset(data);});return()=>{alive.current=false;};},[load]);
 function change<K extends keyof Fields>(key:K,value:Fields[K]){setFields(old=>old?{...old,[key]:value}:old);setReviewed(false);setPreview(null);}
 function select(id:string,nextMode=mode){if(!snapshot)return;setMode(nextMode);reset(snapshot,id);setError('');setNotice('');}
 function parsedFields(){return {...fields!,departures:times.split(/[\s,，]+/).filter(Boolean)};}
 function parsedHolidays(){return {years:years.split(/[\s,，]+/).filter(Boolean).map(Number),holidays:holidays.split('\n').filter(s=>s.trim()).map(line=>{const [date,...name]=line.split('|');return {date:date.trim(),name:name.join('|').trim()};})};}
 function reload(){if(dirty){opener.current=document.activeElement as HTMLElement;dialog.current?.showModal();}else void run(async()=>{const data=await load();if(alive.current)reset(data);});}
 function closeDialog(discard:boolean){dialog.current?.close();if(discard)void run(async()=>{const data=await load();if(alive.current)reset(data);});else opener.current?.focus();}
 const statusLabels:Record<string,string>={scheduled:t('当天正常计划班次','Scheduled service'),finished_for_day:t('当天班次已结束','Service finished for the day'),public_holiday:t('公众假期或周日不运行','No service on this holiday or Sunday'),non_operating_day:t('非运行日','Non-operating day'),outside_service_period:t('超出服务期','Outside service period'),stale:t('资料复核期限已过','Review overdue'),holiday_coverage_unknown:t('该年份假期资料未核验','Holiday year not reviewed')};
 const source=mode==='route'?original?.source??snapshot?.catalog.source:snapshot?.catalog.holiday_source;
 return <section className="shuttle-admin" aria-label={t('校巴维护','Shuttle maintenance')}>
 <div className="shuttle-admin-heading"><div><p className="campus-eyebrow">{t('计划班次 · 人工核验','Scheduled service · Human review')}</p><h2>{t('让下一班车的信息，保持准确。','Keep the next departure accurate.')}</h2><p>{t('选择线路，核对来源，预览后保存。每条线路单独计算复核期限。','Choose a route, review the source, then preview and save. Each route has its own review deadline.')}</p></div><button className="campus-button campus-secondary" disabled={busy} onClick={reload}>{t('重新加载','Reload')}</button></div>
 {error?<p role="alert" className="campus-error">{error}</p>:null}{notice?<p role="status" className="campus-status">{notice}</p>:null}
 {!snapshot?<p>{busy?t('正在读取时刻表…','Loading timetable…'):t('资料尚未加载，请重试。','No catalog loaded. Retry.')}</p>:<>
 <div className="campus-actions"><button className="campus-button campus-secondary" aria-pressed={mode==='route'} disabled={busy||dirty} onClick={()=>select(routeId,'route')}>{t('线路时刻','Timetables')}</button><button className="campus-button campus-secondary" aria-pressed={mode==='holidays'} disabled={busy||dirty} onClick={()=>select(routeId,'holidays')}>{t('公众假期','Public holidays')}</button><span className="campus-note">{t('目录版本','Catalog revision')} {snapshot.revision}</span></div>
 {dirty?<p className="campus-note" role="status">{t('有未保存修改。保存后可切换；也可通过“重新加载”放弃草稿。','Unsaved changes. Save to switch, or use Reload to discard the draft.')}</p>:null}
 {mode==='route'?<label>{t('选择线路与方向','Route and direction')}<select disabled={busy||dirty} value={routeId} onChange={e=>select(e.target.value)}>{snapshot.catalog.routes.map(r=><option key={r.id} value={r.id}>{r.name[language]}</option>)}</select></label>:<p>{t('编辑完整假期清单。覆盖年份代表整年已核对，不能只填几个节日就宣称全年完整。','Edit the full holiday calendar. A covered year means the entire year was reviewed, not just a few dates.')}</p>}
 <div className="shuttle-admin-source"><span className="shuttle-step">1</span><div><h3>{t('核对官方来源','Review the official source')}</h3>{source?<><a href={source.url} target="_blank" rel="noreferrer">{t('打开官方页面','Open official page')} ↗</a><p className="campus-note">{t('当前资料抓取于','Current evidence captured')} {source.retrieved_at}<br/>{t('复核期限','Review due')} {mode==='route'?original?.refresh_due_at:snapshot.catalog.holiday_refresh_due_at}</p></>:null}<button className="campus-button campus-secondary" disabled={busy} onClick={()=>void run(async()=>{const result=await request<Check>('/admin/campus/source-checks',{target_kind:mode==='route'?'shuttle_timetable':'shuttle_holidays',target_id:mode==='route'?'catalog':'calendar'});if(alive.current){setCheck(result);setReviewed(false);setNotice(t('来源已捕获。请阅读原文并核对待保存的内容。','Source captured. Read the source and verify your edits.'));}})}>{t('获取本次来源证据','Capture source evidence')}</button>{check?<p className="campus-note">{t('本次捕获','Captured now')} {new Date(check.retrieved_at).toISOString()}<br/><span className="campus-hash">SHA-256 {check.sha256}</span></p>:null}</div></div>
 <form onSubmit={e=>{e.preventDefault();if(!check||!reviewed||(mode==='route'&&!preview))return;void run(async()=>{const path=mode==='route'?'/admin/campus/shuttle/routes/'+routeId:'/admin/campus/shuttle/holidays';const result=await request<Snapshot>(path,{revision:snapshot.revision,source_check_id:check.id,reason,...(mode==='route'?{fields:parsedFields()}:parsedHolidays())});if(alive.current){reset(result);setNotice(t('已保存。学生下一次查询会读取这个版本；仍为计划班次，非实时车况。','Saved. Student queries now read this revision. Scheduled service, not live tracking.'));}});}}>
 <h3><span className="shuttle-step">2</span> {t('编辑已核对资料','Edit reviewed information')}</h3>
 {mode==='route'&&fields?<>
 <div className="shuttle-fields">{(['zh','en'] as const).map(lang=><label key={lang}>{lang==='zh'?'线路名称 · 中文':'Route name · English'}<input required maxLength={2000} disabled={busy} value={fields.name[lang]} onChange={e=>change('name',{...fields.name,[lang]:e.target.value})}/></label>)}<label>{t('上车地点','Boarding location')}<input required disabled={busy} value={fields.origin} onChange={e=>change('origin',e.target.value)}/></label><label>{t('目的地','Destination')}<input required disabled={busy} value={fields.destination} onChange={e=>change('destination',e.target.value)}/></label><label>{t('服务开始日期','Service start')}<input type="date" required disabled={busy} value={fields.valid_from} onInput={e=>change('valid_from',e.currentTarget.value)} onChange={e=>change('valid_from',e.target.value)}/></label><label>{t('服务结束日期','Service end')}<input type="date" required disabled={busy} value={fields.valid_to} onInput={e=>change('valid_to',e.currentTarget.value)} onChange={e=>change('valid_to',e.target.value)}/></label><label>{t('费用（港币分；空白为未知）','Fare (HK cents; blank means unknown)')}<input type="number" min={0} max={100000} step={1} disabled={busy} value={fields.fare_minor??''} onChange={e=>change('fare_minor',e.target.value===''?null:Number(e.target.value))}/></label><label>{t('乘车资格','Eligibility')}<select disabled={busy} value={fields.eligibility} onChange={e=>change('eligibility',e.target.value)}><option value="student_only">{t('仅学生','Students only')}</option><option value="student_or_staff">{t('学生或教职员','Students or staff')}</option></select></label></div>
 <fieldset className="shuttle-weekdays"><legend>{t('运行日','Operating weekdays')}</legend>{[1,2,3,4,5,6,0].map((day,i)=><label key={day}><input type="checkbox" disabled={busy} checked={fields.weekdays.includes(day)} onChange={e=>change('weekdays',e.target.checked?[...fields.weekdays,day].sort():fields.weekdays.filter(d=>d!==day))}/>{(zh?['一','二','三','四','五','六','日']:['Mon','Tue','Wed','Thu','Fri','Sat','Sun'])[i]}</label>)}</fieldset>
 <label className="campus-maintenance-confirm"><input type="checkbox" disabled={busy} checked={fields.exclude_public_holidays} onChange={e=>change('exclude_public_holidays',e.target.checked)}/>{t('公众假期及周日不运行','Exclude public holidays and Sundays')}</label>
 <label>{t('发车时间（香港时间，一行一班，按先后顺序）','Departures (Hong Kong time, one per line, ascending)')}<textarea rows={5} required disabled={busy} value={times} onChange={e=>{setTimes(e.target.value);setPreview(null);setReviewed(false);}}/></label><label>{t('运行说明','Service notes')}<textarea rows={2} maxLength={2000} disabled={busy} value={fields.note} onChange={e=>change('note',e.target.value)}/></label>
 </>:<><label>{t('已核验完整年份（逗号分隔）','Fully reviewed years (comma separated)')}<input required disabled={busy} value={years} onChange={e=>{setYears(e.target.value);setReviewed(false);}}/></label><label>{t('假期清单：日期 | 名称，每行一项','Holidays: date | name, one per line')}<textarea rows={12} required disabled={busy} value={holidays} onChange={e=>{setHolidays(e.target.value);setReviewed(false);}}/></label><p className="campus-note">{t('原清单','Previous calendar')}: {snapshot.catalog.holidays.length} · {t('待保存','Pending')}: {holidays.split('\n').filter(s=>s.trim()).length}</p></>}
 <div className="shuttle-review"><h3><span className="shuttle-step">3</span> {t('预览与确认','Preview and confirm')}</h3>{mode==='route'?<><label>{t('查询时间（香港时间）','Query time (Hong Kong)')}<input type="datetime-local" required value={at} disabled={busy} onInput={e=>{setAt(e.currentTarget.value);setPreview(null);setReviewed(false);}} onChange={e=>{setAt(e.target.value);setPreview(null);setReviewed(false);}}/></label><button type="button" className="campus-button campus-secondary" disabled={busy} onClick={()=>void run(async()=>{const result=await request<ShuttleDepartures>('/admin/campus/shuttle/routes/'+routeId+'/preview',{revision:snapshot.revision,fields:parsedFields(),at:at+':00+08:00'});if(alive.current){setPreview(result);setReviewed(false);}})}>{t('预览待保存班次','Preview edited timetable')}</button>{preview?<div className="campus-status" role="status"><strong>{t('预览 · 尚未保存','Preview · Not saved')}</strong><p>{preview.route.name[language]} · {preview.service_date}</p><p>{t('当日时刻表','Day timetable')}: {preview.timetable.map(d=>d.local_time).join(' · ')}</p><p>{t('可用的后续班次','Upcoming when valid')}: {preview.upcoming.map(d=>d.local_time).join(' · ')||'—'}</p><p>{t('当前校验状态','Current validation status')}: {statusLabels[preview.status]??preview.status}</p><p className="campus-note">{t('预览沿用当前资料期限；保存后仅本线路期限更新。','Preview uses existing review dates; saving renews this route only.')}</p></div>:null}</>:<p>{t('请逐年对照官方清单。保存会替换完整假期表，并影响全部遵守假期规则的线路。','Compare every covered year with the official calendar. Saving replaces the holiday table used by all routes that exclude holidays.')}</p>}
 <label>{t('本次修改说明','Reason for this change')}<textarea required minLength={5} maxLength={1000} rows={2} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label><label className="campus-maintenance-confirm"><input type="checkbox" checked={reviewed} disabled={busy||!check||(mode==='route'&&!preview)} onChange={e=>setReviewed(e.target.checked)}/>{t('我已对照官方来源核验全部修改；内容是计划资料。','I reviewed all changes against the official source; this is scheduled information.')}</label><button className="campus-button" disabled={busy||!check||!reviewed||reason.trim().length<5||(mode==='route'&&!preview)}>{busy?t('处理中…','Working…'):t('保存已核对版本','Save reviewed revision')}</button></div>
 </form>
 <button className="campus-button campus-secondary" disabled={busy} onClick={()=>void run(async()=>{const result=await request<History[]>('/admin/campus/history?'+new URLSearchParams({target_kind:mode==='route'?'shuttle':'shuttle_holidays',target_id:mode==='route'?routeId:'calendar'}));if(alive.current){setHistory(result);if(!result.length)setNotice(t('尚无修改记录。','No changes recorded yet.'));}})}>{t('查看修改记录','View change history')}</button>{history.map(h=><details key={h.id}><summary>{h.action} · {new Date(h.created_at).toISOString()}</summary><p>{h.reason}</p><pre className="campus-history">{JSON.stringify({before:h.before,after:h.after},null,2)}</pre></details>)}
 </>}
 <dialog ref={dialog} className="campus-discard-dialog" aria-labelledby="shuttle-discard-title" onCancel={e=>{e.preventDefault();closeDialog(false);}}><h2 id="shuttle-discard-title">{t('放弃草稿并重新加载？','Discard draft and reload?')}</h2><p>{t('未保存输入会被清除，已保存的版本不受影响。','Unsaved input will be cleared. Saved revisions stay unchanged.')}</p><div className="campus-actions"><button className="campus-button" autoFocus onClick={()=>closeDialog(false)}>{t('继续编辑','Keep editing')}</button><button className="campus-button campus-secondary" onClick={()=>closeDialog(true)}>{t('放弃并重新加载','Discard and reload')}</button></div></dialog>
 </section>;
}
