const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const escape = CSS.escape;
const screen=$('#screen'), viewport=$('#viewport');
let manifest=[], designs, current='today', trail=[], dirty=false, busy=false, pendingBack=null, toastTimer, drafts={};
const initialState=()=>({joined:'none',calendar:false,calendarChoice:false,saved:[],task:null,taskDone:false,notices:[],activity:null,read:false,replies:[],activityReplies:[],preferences:{},post:null,event:'library',joinedEvent:'library',selectedPost:'question'});
let state=initialState();
const rootTabs={今天:'today',校园:'campus',发现:'discover',消息:'inbox',我的:'me'};
const backMap={course:'today',task:'today',import:'connections',shuttle:'campus',place:'campus',activity:'discover',join:'activity',confirmed:'activity',waitlisted:'activity',uncertain:'activity',wall:'discover',post:'wall',saved:'me',privacy:'me',empty:'discover',offline:'shuttle',welcome:'today','school-login':'welcome','sis-consent':'school-login'};
const tokenMap={'#f2f2f7':'var(--phone)','#ffffff':'var(--surface)','#1c1c1e':'var(--ink)','#6e6e73':'var(--muted)','#007aff':'var(--blue)','#d9d9de':'var(--line)','#c4c4c9':'var(--tertiary)','#7676801f':'var(--fill)','#ffffffc7':'var(--glass)','#007aff1a':'var(--accent-soft)'};
function byName(root,name){return $$(`[data-pencil-name="${escape(name)}"]`,root);}
function toast(message){clearTimeout(toastTimer);$('#toast').textContent=message;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,3400);}
function bind(el,label,fn,kind){el.setAttribute('role','button');el.setAttribute('tabindex','0');el.setAttribute('aria-label',label);el.dataset.actionKind=kind||'navigation';el.addEventListener('click',e=>{e.stopPropagation();fn();});el.addEventListener('keydown',e=>{if(e.target===el&&(e.key==='Enter'||e.key===' ')){e.preventDefault();e.stopPropagation();fn();}});}
function snapshot(){return {key:current,scroll:viewport.scrollTop};}
function requestBack(target){if(dirty){pendingBack=target;$('#draft-dialog').showModal();return;}goBack(target);}
function goBack(fallback){const prev=trail.pop();render(prev?.key||fallback||backMap[current]||'today','backward',prev?.scroll||0);}
function go(key,kind='forward'){if(!manifest.some(s=>s.key===key))return toast('这个入口暂时不可用。');if(key===current){if(kind==='tab-motion')viewport.scrollTo({top:0,behavior:document.body.classList.contains('reduce')?'instant':'smooth'});return;}trail.push(snapshot());render(key,kind);}
function render(key,kind='forward',scroll=0){const item=manifest.find(s=>s.key===key);if(!item)return;current=key;dirty=false;busy=false;const original=designs.querySelector(`[data-pencil-id="${escape(item.id)}"]`);if(!original)throw new Error('Missing Pen frame '+key);const root=original.cloneNode(true);root.classList.add('pen-screen');
 for(const el of [root,...$$('[style]',root)]){for(const prop of ['background-color','color','border-color','border-top-color','border-bottom-color']){const val=el.style[prop];if(!val)continue;const hex=val.startsWith('rgb')?rgbHex(val):val.toLowerCase();if(prop==='background-color'&&/^#ffffff[0-9a-f]{2}$/.test(hex)&&parseInt(hex.slice(-2),16)>=128){el.style[prop]='var(--glass)';continue;}if(tokenMap[hex]){if(prop==='color'&&hex==='#ffffff'){let parent=el.parentElement;while(parent&&parent!==root){if(parent.style.backgroundColor){if(parent.style.backgroundColor==='var(--ink)')el.style.color='var(--surface)';break;}parent=parent.parentElement;}continue;}el.style[prop]=tokenMap[hex];}}}
 for(const path of $$('svg path[fill]',root)){const fill=path.getAttribute('fill').toLowerCase();if(fill!=='#ffffff'&&tokenMap[fill])path.setAttribute('fill',tokenMap[fill]);}
 root.style.setProperty('position','relative');root.style.removeProperty('left');root.style.removeProperty('top');root.style.width='100%';root.style.borderRadius='0';
 screen.replaceChildren(root);screen.className=kind;screen.setAttribute('aria-busy','false');
 const used=new Set();for(const link of item.links){for(const el of byName(root,link.name)){if(used.has(el))continue;used.add(el);bind(el,link.name.replace(/^Button /,''),()=>activate(link.target,link.name));}}
 // Component instance names remain stable in Pen exports, including dark variants.
 for(const [label,target] of Object.entries(rootTabs)){for(const el of byName(root,'Tab '+label))bind(el,label,()=>{if(dirty){pendingBack=target;$('#draft-dialog').showModal();return;}go(target,'tab-motion');},'tab');}
 for(const el of $$('[data-pencil-name]',root)){const name=el.dataset.pencilName;if(!used.has(el)&&['Back','Back button','Button chevron-left'].includes(name)&&el.tagName!=='svg')bind(el,'返回',()=>requestBack(item.back||backMap[key]));}
 // Legacy primary buttons have a Button prefix; resolve exact model action labels.
 for(const link of item.links)for(const el of byName(root,'Button '+link.name)){if(used.has(el))continue;used.add(el);bind(el,link.name,()=>activate(link.target,link.name));}
 for(const field of item.fields){const host=$(`[data-pencil-id="${escape(field.id)}"]`,root);if(!host)continue;const value=byName(host,'Field value')[0];if(!value)continue;const multiline=/正文|内容|描述|原因|备注/.test(field.label)||field.value?.includes('\n');const input=document.createElement(multiline?'textarea':'input');input.className='field-input';input.setAttribute('aria-label',field.label);input.maxLength=multiline?2000:160;if(multiline)input.rows=3;input.value=drafts[key]?.[field.label]??field.value??'';if(key==='delete-account'){input.placeholder='输入“删除”';input.value=drafts[key]?.[field.label]||'';}input.addEventListener('input',()=>{drafts[key]??={};drafts[key][field.label]=input.value;dirty=true;input.removeAttribute('aria-invalid');});value.replaceChildren(input);}
 if(key==='search')installSearch(root);
 if(key==='discover')for(const el of $$('[data-pencil-name="Filters"]>[data-pencil-name]',root))bind(el,el.textContent.trim(),()=>{const name=el.dataset.pencilName;for(const pill of $$('[data-pencil-name="Filters"]>[data-pencil-name]',root))pill.style.opacity=pill===el?'1':'.55';for(const card of $$('[data-pencil-name^="Activity card "]',root)){card.style.display=name==='Pill 全部'||name==='Pill 筛选'||(name==='Pill 安静共处'?card.dataset.pencilName.includes('图书馆'):!card.dataset.pencilName.includes('图书馆'))?'flex':'none';}toast(name==='Pill 筛选'?'可以按安静共处或随意交流选择活动。':'已显示'+el.textContent.trim()+'的活动');},'filter');
 if(key==='join'){const toggle=byName(root,'Switch')[0];if(toggle){const paint=()=>{toggle.style.backgroundColor=state.calendarChoice?'#34c759':'var(--fill)';toggle.style.justifyContent=state.calendarChoice?'flex-end':'flex-start';toggle.setAttribute('aria-checked',String(state.calendarChoice));};bind(toggle,'同时保存到个人日程',()=>{state.calendarChoice=!state.calendarChoice;paint();},'switch');toggle.setAttribute('role','switch');paint();}for(const el of $$('[data-pencil-name]',root))if(el.childElementCount===0&&el.textContent.trim()==='取消'&&getComputedStyle(el).opacity!=='0')bind(el,'取消报名',()=>requestBack('activity'));}
 applyState(root,key);applyContentVariant(root,key);
 $('#page-title').textContent=item.title.replaceAll('\\n',' ');$('#page-stage').textContent=item.stage==='MVP'?'设计演示 · 示例数据':item.stage+' · 设计概念';
 history.replaceState(null,'','#'+key);updateCatalog();requestAnimationFrame(()=>{viewport.scrollTop=scroll;const h=byName(root,'Page title')[0]||byName(root,'Title')[0];if(h){h.tabIndex=-1;h.focus({preventScroll:true});}});
}
function rgbHex(rgb){const nums=rgb.match(/[\d.]+/g).map(Number);return '#'+nums.slice(0,3).map(n=>Math.round(n).toString(16).padStart(2,'0')).join('')+(nums.length===4?Math.round(nums[3]*255).toString(16).padStart(2,'0'):'');}
function captureFields(){return Object.fromEntries($$('.field-input',screen).map(el=>[el.getAttribute('aria-label'),el.value.trim()]));}
function validate(){let first;for(const el of $$('.field-input',screen)){if(!el.value.trim()&&!/选填|备注|笔记/.test(el.getAttribute('aria-label'))){el.setAttribute('aria-invalid','true');first??=el;}}if(first){first.focus();toast('先填写'+first.getAttribute('aria-label')+'，内容不会丢失。');return false;}return true;}
async function activate(target,label){if(busy)return;const from=current;if(label==='返回'||label==='返回修改'||label==='再想一想'){requestBack(target);return;}if(target?.startsWith('@'))return localAction(target,label);if(target==='draft'){pendingBack=backMap[current]||manifest.find(s=>s.key===current)?.back||'today';$('#draft-dialog').showModal();return;}
 if(label.includes('Activity card '))state.event=label.includes('海边')?'beach':'library';else if(label.includes('Row 图书馆，自习一小时'))state.event='library';
 if(label.startsWith('Post ')){state.selectedPost=label.includes('海边')?'sea':label.includes('社团')?'club':'question';state.post=null;}
 if(from==='activity-chat'&&label==='发送示例回复'){const reply=captureFields()['回复'];if(!reply)return toast('写一句回复再发送。');state.activityReplies.push(reply);state.notices.unshift('活动讨论已添加回复');delete drafts[from];dirty=false;render(from,'tab-motion',viewport.scrollTop);toast('回复已保存在本次演示中。');return;}
 if(target===current){state.preferences[from]=label;for(const el of byName(screen,label))el.classList.toggle('selected-preference');toast('已选择：'+label);return;}
 const isSave=/保存|发布|预览|提交|继续到/.test(label);if(isSave&&!validate())return;if(from==='delete-account'&&target==='deleted'&&captureFields()['确认操作']!=='删除')return toast('输入“删除”才能继续这个演示。');
 if(from==='task-edit'&&label==='保存安排'){state.task=captureFields();state.taskDone=false;dirty=false;toast('安排已保存，今天与课程一起更新。');}
 if(from==='create-activity'&&target==='activity-preview'){drafts[from]=captureFields();dirty=false;}
 if(from==='activity-preview'&&target==='manage-activity'){state.activity={...(drafts['create-activity']||{})};toast('示例活动已发布到本次演示。');}
 if(from==='notes'&&label==='保存笔记'){drafts[from]=captureFields();toast('笔记已保存到本次演示。');dirty=false;}
 if(from==='join'&&target==='confirmed'){busy=true;screen.setAttribute('aria-busy','true');await new Promise(r=>setTimeout(r,350));const scenario=$('#scenario').value;target=scenario==='full'?'waitlisted':scenario==='offline'?'uncertain':'confirmed';}
 if(from==='uncertain'&&target==='confirmed'){target=$('#scenario').value==='offline'?'uncertain':$('#scenario').value==='full'?'waitlisted':'confirmed';if(target==='uncertain')return toast('结果仍待确认。可切换报名情境后重试。');}
 if(target==='confirmed'||target==='waitlisted'){state.joined=target;state.joinedEvent=state.event;state.calendar=state.calendarChoice;state.notices.unshift(target==='confirmed'?'报名已确认':'已加入候补');state.read=false;}
 if(target==='withdrawn'){state.joined='none';state.calendar=false;state.notices.unshift('已退出活动');state.read=false;}
 if(target==='task-completed')state.taskDone=true;if(from==='task-completed'&&target==='task')state.taskDone=false;
 if(isSave&&hasFields()){drafts[from]=captureFields();dirty=false;if(!['create-activity','task-edit','delete-account'].includes(from))toast('已保存本次演示中的修改。');}
 if(from==='wall-compose'&&target==='post'){state.post=captureFields();state.notices.unshift('校园墙帖子已在演示中发布');state.read=false;}
 if(from==='cancel-activity'&&target==='cancelled'){state.activity=null;state.notices.unshift('活动已取消');}
 go(target);
}
function hasFields(){return !!$('.field-input',screen);}
function localAction(action,label){if(action==='@save'){const key=['shuttle','place'].includes(current)?current:'activity';state.saved=state.saved.includes(key)?state.saved.filter(x=>x!==key):[...state.saved,key];toast(state.saved.includes(key)?'已收藏，可以到「我的收藏」查看。':'已移除收藏。');}else if(action==='@calendar'){state.calendar=!state.calendar;toast(state.calendar?'已加入今天的演示日程。':'已从演示日程移除。');}else if(action==='@read'){state.read=true;toast('全部消息已标记为已读。');render(current,'tab-motion',viewport.scrollTop);}else if(action==='@private')toast('你的课表和私人任务仅自己可见。');else if(action==='@share'){navigator.clipboard?.writeText(location.href).then(()=>toast('演示页面链接已复制。')).catch(()=>toast('本页地址可用于分享本机演示。'));}else if(action==='@filter'){toast('已切换为「'+label.replace('Segment ','')+'」');$$('.demo-update',screen).forEach(el=>el.hidden=label.includes('收藏')&&el.dataset.kind==='joined'||label.includes('参与')&&el.dataset.kind==='saved');}else if(action==='@delete-task'){state.task=null;toast('已从演示中移除新增安排。');go('today');}else if(action==='@export'){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='campus-demo-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('已导出本次演示数据。');}}
function note(root,text,target,kind){const box=document.createElement('div');box.className='demo-update';box.dataset.kind=kind||'status';if(target){const b=document.createElement('button');b.textContent=text;b.onclick=()=>go(target);box.append(b);}else box.textContent=text;const content=byName(root,'Scrollable content')[0]||byName(root,'Content')[0]||root;content.append(box);return box;}
function applyState(root,key){if(state.preferences[key])for(const el of byName(root,state.preferences[key]))el.classList.add('selected-preference');if(key==='activity-chat')for(const reply of state.activityReplies)note(root,reply);if(key==='post'&&state.post)note(root,state.post['标题']+'\n'+state.post['正文']);if(['today','course'].includes(key)&&state.task)note(root,(state.taskDone?'✓ ':'○ ')+state.task['名称']+' · '+state.task['时间'],'task','task');if(['today','course','task'].includes(key)&&state.taskDone)note(root,'✓ 任务已完成 · 私人任务，不代表学校作业已提交。');if(key==='task'&&state.task){const title=byName(root,'Title')[0];if(title)title.textContent=state.task['名称'];note(root,'已保存：'+Object.values(state.task).join(' · '));}
 if(['today','saved','activity','inbox'].includes(key)&&state.calendar){const box=note(root,(state.joined==='waitlisted'?'候补中 · 尚未获得名额':'报名已确认')+' · '+(state.joinedEvent==='beach'?'课后，去海边走走':'图书馆，自习一小时'),'activity','joined');box.querySelector('button').onclick=()=>{state.event=state.joinedEvent;go('activity');};}
 if(key==='inbox'){for(const msg of state.notices)note(root,(state.read?'已读 · ':'● ')+msg,'activity');if(!state.notices.length)note(root,'以上为消息样例。完成一次演示报名，这里会显示对应更新。');}
 if(key==='saved')for(const s of state.saved)note(root,'已收藏 · '+(s==='shuttle'?'校巴路线':s==='place'?'图书馆':'自习活动'),s,'saved');
 if(['activity-preview','manage-activity'].includes(key)){const a=state.activity||drafts['create-activity'];if(a)note(root,Object.entries(a).map(([k,v])=>k+'：'+v).join('\n'),'create-activity');}
 if(key==='course'&&drafts.notes)note(root,'已保存笔记 · '+drafts.notes['标题'],'notes');
 if(key==='post'){const form=document.createElement('form');form.className='demo-update';const input=document.createElement('input');input.className='field-input';input.placeholder='留一句友善的回复';input.setAttribute('aria-label','回复内容');input.maxLength=500;input.required=true;const send=document.createElement('button');send.textContent='发送演示回复';send.type='submit';form.append(input,send);form.onsubmit=e=>{e.preventDefault();if(!input.value.trim())return;state.replies.push(input.value.trim());state.notices.unshift('校园墙回复已添加');render('post','tab-motion',viewport.scrollTop);toast('回复已留在本次演示中。');};root.append(form);for(const reply of state.replies)note(root,reply);}}
function installSearch(root){const input=$('.field-input',root);if(!input)return;const result=document.createElement('div');result.className='demo-update';input.insertAdjacentElement('afterend',result);input.addEventListener('input',()=>{result.replaceChildren();const q=input.value.trim();if(!q)return;const matches=manifest.filter(m=>m.key!=='search'&&m.title.includes(q)).slice(0,5);if(!matches.length)result.textContent='暂时没找到，试试课程、活动或邮箱。';for(const m of matches){const b=document.createElement('button');b.textContent=m.title;b.onclick=()=>{dirty=false;go(m.key);};result.append(b);}});}
function applyContentVariant(root,key){let replacements=[];if(state.event==='beach'&&['activity','join','confirmed','waitlisted','uncertain','withdraw','withdrawn','activity-chat','participants'].includes(key)){replacements=[['留一个小时，一起自习。','课后，去海边走走'],['带上自己的书或电脑。名额不含组织者。','穿舒适的鞋。名额不含组织者。'],['10 月 5 日 · 16:00','10 月 5 日 · 17:30'],['图书馆，自习一小时','课后，去海边走走'],['图书馆入口','海边步道入口'],['16:00–17:00','17:30–18:30'],['16:00—17:00','17:30—18:30'],['安静共处 · 普通话 / English','随意交流 · English'],['安静共处 · 本地演示','随意交流 · 本地演示'],['2 / 4 人已确认','3 / 6 人已确认'],['不需要准备话题，各自做自己的事。','沿着海边慢慢走，不需要提前准备话题。'],['入口集合后一起找座位。带上你的书或电脑；中途有事可以离开。','在海边步道入口集合，走到哪里算哪里。穿舒适的鞋，中途有事可以离开。']];const hero=byName(root,'Hero image')[0],photo=designs.querySelector('[data-pencil-id="ozvy9"] [data-pencil-name="Image"]');if(hero&&photo)hero.style.backgroundImage=photo.style.backgroundImage;}
 if(key==='post'&&!state.post&&state.selectedPost!=='question')replacements=state.selectedPost==='sea'?[['怎么找到课室？','今天的海边很好看'],['第一次去教学楼，电梯和课室编号该怎么找？','下课后沿着海边走了一会儿，风很舒服。你们还有什么喜欢的校园角落？'],['求助','校园生活'],['先在官方地图搜索课室编号，确认电梯区域。','傍晚光线很柔和，慢慢走一圈就很好。']]:[['怎么找到课室？','第一次参加社团活动'],['第一次去教学楼，电梯和课室编号该怎么找？','第一次去摄影小组有点紧张，可以只旁听和看看大家的作品吗？'],['先在官方地图搜索课室编号，确认电梯区域。','可以的，先观察也很好，不需要一开始就介绍自己。']];
 const walker=document.createTreeWalker(root,NodeFilter.SHOW_TEXT);while(walker.nextNode()){const node=walker.currentNode;if(node.parentElement.closest('input,textarea'))continue;for(const [from,to] of replacements)node.textContent=node.textContent.replaceAll(from,to);}}
function updateCatalog(){const q=$('#search').value.trim().toLowerCase();const shown=manifest.filter(m=>(m.title+' '+m.key).toLowerCase().includes(q));$('#count').textContent=shown.length+' / '+manifest.length+' 个页面与状态';$('#page-list').replaceChildren(...shown.map(m=>{const b=document.createElement('button');b.textContent=m.title.replaceAll('\\n',' ');const small=document.createElement('small');small.textContent=m.key+' · '+(m.stage==='MVP'?'基础设计':m.stage);b.append(small);if(m.key===current)b.setAttribute('aria-current','page');b.onclick=()=>{go(m.key);$('#catalog').hidden=true;$('#catalog-toggle').setAttribute('aria-expanded','false');};return b;}));}
$('#back').onclick=()=>requestBack(backMap[current]);$('#theme').onclick=()=>{const dark=document.body.dataset.theme!=='dark';document.body.dataset.theme=dark?'dark':'light';$('#theme').setAttribute('aria-label',dark?'切换浅色外观':'切换深色外观');};$('#reduce').onclick=()=>{$('#reduce').setAttribute('aria-pressed',String(document.body.classList.toggle('reduce')));};$('#restart').onclick=()=>{state=initialState();drafts={};trail=[];dirty=false;$('#scenario').value='available';render('today','tab-motion');toast('演示已重置。');};for(const b of $$('[data-go]'))b.onclick=()=>go(b.dataset.go);
$('#catalog-toggle').onclick=()=>{$('#catalog').hidden=!$('#catalog').hidden;$('#catalog-toggle').setAttribute('aria-expanded',String(!$('#catalog').hidden));if(!$('#catalog').hidden)$('#search').focus();};$('#catalog-close').onclick=()=>{$('#catalog').hidden=true;$('#catalog-toggle').setAttribute('aria-expanded','false');$('#catalog-toggle').focus();};$('#search').oninput=updateCatalog;
$('#draft-keep').onclick=()=>{drafts[current]=captureFields();dirty=false;$('#draft-dialog').close();goBack(pendingBack);toast('草稿已保留。');};$('#draft-edit').onclick=()=>{$('#draft-dialog').close();$('.field-input',screen)?.focus();};$('#draft-discard').onclick=()=>{delete drafts[current];dirty=false;$('#draft-dialog').close();goBack(pendingBack);toast('未保存的修改已放弃。');};window.addEventListener('hashchange',()=>{const key=location.hash.slice(1);if(manifest.some(m=>m.key===key)&&key!==current)go(key);});
try{const [m,h]=await Promise.all([fetch('manifest.json').then(r=>r.json()),fetch('all-screens.html').then(r=>r.text())]);manifest=m;designs=new DOMParser().parseFromString(h,'text/html');render(manifest.some(m=>m.key===location.hash.slice(1))?location.hash.slice(1):'today','tab-motion');window.campusReview={screens:manifest.map(({key,title,stage})=>({key,title,stage})),go:key=>go(key),getState:()=>structuredClone({current,state,drafts,dirty}),audit:()=>manifest.map(m=>({key:m.key,found:!!designs.querySelector(`[data-pencil-id="${escape(m.id)}"]`),missing:m.links.filter(l=>!l.target?.startsWith('@')&&!manifest.some(s=>s.key===l.target)).map(l=>l.target)}))};}catch(e){screen.textContent='演示未能加载。请使用本地服务打开本目录，再刷新页面。';console.error(e);}
