import {createHash,randomUUID} from 'node:crypto';
import type {DatabaseSync} from 'node:sqlite';
import {z} from 'zod';
import {transaction} from '../database.js';
import {ApiError} from '../errors.js';
import {blocked,unblockedSql} from './access.js';
import {keySchema,version} from './schemas.js';
import type {WallPost,WallReply} from './wall-types.js';
export const postSchema=z.object({kind:z.enum(['wall','help']),topic:z.enum(['question','share','buddy','market']).optional(),title:z.string().trim().min(1).max(160),body:z.string().trim().min(1).max(5000),visibility:z.enum(['public','members'])}).strict();
export const postQuery=z.object({kind:z.enum(['wall','help']).optional(),topic:z.enum(['question','share','buddy','market']).optional(),status:z.enum(['open','resolved','closed']).optional(),q:z.string().trim().max(120).optional(),mine:z.literal('true').optional(),cursor:z.string().uuid().optional()}).strict();
type Row={id:string;author_id:string;kind:WallPost['kind'];topic:WallPost['topic'];reply_count:number;title:string;body:string;visibility:WallPost['visibility'];status:WallPost['status'];version:number;moderation_state:string;created_at:number;updated_at:number;display_name:string;banned_at:number|null};
export function createWallStore(db:DatabaseSync,now:()=>number){
 const select="SELECT p.*,u.display_name,u.banned_at,(SELECT COUNT(*) FROM wall_replies r WHERE r.post_id=p.id AND r.moderation_state='visible') AS reply_count FROM wall_posts p JOIN users u ON u.id=p.author_id";
 function raw(id:string,viewer:string|null){const r=db.prepare(select+' WHERE p.id=?').get(id) as Row|undefined;if(!r||r.moderation_state!=='visible'||r.banned_at!==null||r.visibility==='members'&&!viewer||blocked(db,viewer,r.author_id))throw new ApiError(404,'POST_NOT_FOUND','Post unavailable.');return r;}
 function get(id:string,viewer:string|null):WallPost{const r=raw(id,viewer);return {id:r.id,kind:r.kind,topic:r.topic??(r.kind==='help'?'question':'share'),reply_count:Number(r.reply_count??0),title:r.title,body:r.body,visibility:r.visibility,status:r.status,version:r.version,created_at:new Date(r.created_at).toISOString(),updated_at:new Date(r.updated_at).toISOString(),is_demo:true,author:{id:r.author_id,display_name:r.display_name||'Campus member'},is_mine:r.author_id===viewer};}
 function retry<T>(user:string,scope:string,payload:unknown,key:unknown,write:()=>string,read:(id:string)=>T){const k=keySchema.parse(key),fingerprint=createHash('sha256').update(JSON.stringify(payload)).digest('hex');return transaction(db,()=>{db.prepare('DELETE FROM write_keys WHERE expires_at<=?').run(now());const old=db.prepare('SELECT fingerprint,resource_id FROM write_keys WHERE owner_id=? AND scope=? AND key=?').get(user,scope,k);if(old){if(old.fingerprint!==fingerprint)throw new ApiError(409,'IDEMPOTENCY_CONFLICT','Retry content differs.');try{return read(String(old.resource_id));}catch(e){if(e instanceof ApiError&&e.status===404)throw new ApiError(410,'RECORD_REMOVED','Original content removed.');throw e;}}const id=write();db.prepare('INSERT INTO write_keys VALUES (?,?,?,?,?,?)').run(user,scope,k,fingerprint,id,now()+86400000);return read(id);});}
 function create(user:string,body:unknown,key:unknown){const v=postSchema.parse(body);return retry(user,'wall:create',v,key,()=>{if(Number(db.prepare('SELECT COUNT(*) AS n FROM wall_posts WHERE author_id=? AND created_at>?').get(user,now()-86400000)!.n)>=10)throw new ApiError(429,'POST_LIMIT','Daily post limit reached.');const id=randomUUID();db.prepare('INSERT INTO wall_posts(id,author_id,kind,topic,title,body,visibility,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?)').run(id,user,v.kind,v.kind==='help'?'question':(v.topic&&v.topic!=='question'?v.topic:'share'),v.title,v.body,v.visibility,now(),now());return id;},id=>get(id,user));}
 function list(user:string|null,q:z.infer<typeof postQuery>){if(q.mine&&!user)throw new ApiError(401,'AUTH_REQUIRED','Sign in to see your posts.');const clauses=["p.moderation_state='visible'",'u.banned_at IS NULL'],args:(string|number)[]=[];if(!user)clauses.push("p.visibility='public'");else{clauses.push(unblockedSql('p.author_id'));args.push(user,user);}if(q.mine){clauses.push('p.author_id=?');args.push(user!);}for(const field of ['kind','topic','status'] as const)if(q[field]){clauses.push(`p.${field}=?`);args.push(q[field]!);}if(q.q){clauses.push("instr(lower(p.title || ' ' || p.body),lower(?))>0");args.push(q.q);}if(q.cursor){const r=raw(q.cursor,user);clauses.push('(p.created_at<? OR (p.created_at=? AND p.id<?))');args.push(r.created_at,r.created_at,r.id);}const rows=db.prepare(select+' WHERE '+clauses.join(' AND ')+' ORDER BY p.created_at DESC,p.id DESC LIMIT 21').all(...args) as Row[];return {items:rows.slice(0,20).map(r=>get(r.id,user)),next_cursor:rows.length>20?rows[19].id:null};}
 function own(user:string,id:string,expected:number){const r=raw(id,user);if(r.author_id!==user)throw new ApiError(403,'AUTHOR_REQUIRED','Only the author can change this post.');if(r.version!==expected)throw new ApiError(409,'VERSION_CONFLICT','Post changed. Reload first.');return r;}
 function update(user:string,id:string,body:unknown){const v=z.object({version,title:z.string().trim().min(1).max(160).optional(),body:z.string().trim().min(1).max(5000).optional(),status:z.enum(['open','resolved','closed']).optional()}).strict().refine(v=>v.title!==undefined||v.body!==undefined||v.status!==undefined).parse(body);return transaction(db,()=>{const r=own(user,id,v.version);if(v.status&&((r.kind==='help'&&v.status==='closed')||(r.kind==='wall'&&v.status==='resolved')))throw new ApiError(400,'INVALID_STATUS','Use resolved for help or closed for wall discussions.');db.prepare('UPDATE wall_posts SET title=?,body=?,status=?,version=version+1,updated_at=? WHERE id=?').run(v.title??r.title,v.body??r.body,v.status??r.status,now(),id);if(v.status==='resolved'&&r.status!=='resolved'){for(const x of db.prepare('SELECT DISTINCT author_id FROM wall_replies WHERE post_id=?').all(id))if(x.author_id!==user&&!blocked(db,user,String(x.author_id)))db.prepare("INSERT INTO notifications(owner_id,post_id,kind,created_at) VALUES (?,?,'post_resolved',?)").run(String(x.author_id),id,now());}return get(id,user);});}
 function remove(user:string,id:string,body:unknown){const v=z.object({version}).strict().parse(body);return transaction(db,()=>{own(user,id,v.version);db.prepare('DELETE FROM wall_posts WHERE id=?').run(id);return {deleted:true};});}
 function reply(id:number,postId:string,user:string|null):WallReply{raw(postId,user);const r=db.prepare("SELECT r.*,u.display_name,u.banned_at FROM wall_replies r JOIN users u ON u.id=r.author_id WHERE r.id=? AND r.post_id=? AND r.moderation_state='visible'").get(id,postId);if(!r||r.banned_at!==null||blocked(db,user,String(r.author_id)))throw new ApiError(404,'REPLY_NOT_FOUND','Reply unavailable.');return {id:Number(r.id),post_id:postId,body:String(r.body),version:Number(r.version),created_at:new Date(Number(r.created_at)).toISOString(),author:{id:String(r.author_id),display_name:String(r.display_name)||'Campus member'},is_mine:r.author_id===user};}
 function replies(user:string|null,id:string,cursor?:number){raw(id,user);const rows=db.prepare("SELECT r.id FROM wall_replies r JOIN users u ON u.id=r.author_id WHERE r.post_id=? AND r.id<? AND r.moderation_state='visible' AND u.banned_at IS NULL"+(user?' AND '+unblockedSql('r.author_id'):'')+' ORDER BY r.id DESC LIMIT 51').all(id,cursor??Number.MAX_SAFE_INTEGER,...(user?[user,user]:[]));return {items:rows.slice(0,50).map(r=>reply(Number(r.id),id,user)),next_cursor:rows.length>50?Number(rows[49].id):null};}
 function addReply(user:string,id:string,body:unknown,key:unknown){const v=z.object({body:z.string().trim().min(1).max(2000)}).strict().parse(body);return retry(user,'wall:reply:'+id,v,key,()=>{const post=raw(id,user);if(post.status!=='open')throw new ApiError(409,'DISCUSSION_CLOSED','This discussion is closed.');if(Number(db.prepare('SELECT COUNT(*) AS n FROM wall_replies WHERE author_id=? AND created_at>?').get(user,now()-86400000)!.n)>=40)throw new ApiError(429,'REPLY_LIMIT','Daily reply limit reached.');const row=db.prepare('INSERT INTO wall_replies(post_id,author_id,body,created_at) VALUES (?,?,?,?)').run(id,user,v.body,now());if(post.author_id!==user)db.prepare("INSERT INTO notifications(owner_id,post_id,kind,created_at) VALUES (?,?,'post_reply',?)").run(post.author_id,id,now());return String(row.lastInsertRowid);},cid=>reply(Number(cid),id,user));}
 function removeReply(user:string,id:string,cid:number,body:unknown){const v=z.object({version}).strict().parse(body);return transaction(db,()=>{const r=reply(cid,id,user);if(!r.is_mine)throw new ApiError(404,'REPLY_NOT_FOUND','Reply unavailable.');if(r.version!==v.version)throw new ApiError(409,'VERSION_CONFLICT','Reply changed.');db.prepare('DELETE FROM wall_replies WHERE id=?').run(cid);return {deleted:true};});}
 function exportAll(user:string){return {posts:db.prepare('SELECT id,kind,title,body,visibility,status,version,created_at,updated_at FROM wall_posts WHERE author_id=?').all(user),replies:db.prepare('SELECT id,post_id,body,version,created_at FROM wall_replies WHERE author_id=?').all(user)};}
 return {get,create,list,update,remove,reply,replies,addReply,removeReply,exportAll};
}
