export const studyStrings = {
  zh: {
    title:'今天，按自己的节奏', private:'学习安排仅自己可见', day:'日程', week:'本周', courses:'课程', all:'全部记录',zone:'显示时区',
    add:'添加', back:'返回', previous:'上一段', next:'下一段', today:'回到今天', refresh:'刷新', empty:'这里还没有安排。',
    event:'日程',task:'任务',note:'私人笔记',material:'资料链接',course:'课程', edit:'编辑',remove:'删除',save:'保存',cancel:'取消',
    confirmDelete:'确定删除这条记录？',detach:'删除课程会解绑相关记录，保留你的日程、任务和笔记。',
    name:'标题',code:'课程代码（可选）',body:'内容（可选）',location:'地点（可选）',url:'资料网址',
    courseChoice:'关联课程',noCourse:'不关联课程',allDay:'全天',timed:'指定时间',date:'开始日期',endDate:'结束日期（不包含当天，可留空）',
    start:'开始时间',end:'结束时间（可留空）',format:'日期：YYYY-MM-DD；时间：YYYY-MM-DD HH:mm，按香港时间。',
    due:'截止',noDue:'无截止时间',dateDue:'仅日期',timeDue:'日期和时间',dueDate:'截止日期',dueTime:'截止时间',
    complete:'标记完成',reopen:'重新打开',done:'已完成',open:'待完成',active:'有效',cancelled:'已取消',cancelEvent:'取消日程',restoreEvent:'恢复日程',
    unknownEnd:'结束时间未提供',undated:'暂未设置截止',viewLink:'打开资料',manual:'本人维护 · 不代表学校正式选课',
    loading:'正在读取…',error:'读取失败，原有记录未清空。请重试。',conflict:'这条记录已经发生变化。请返回刷新后重新编辑；本次输入尚未保存。',
    invalid:'请检查标题、日期、时间和网址。',saveError:'保存未完成，输入已保留。可以重试。',
    allDayLabel:'全天',unconfirmed:'记录已提交，正在刷新列表。',
  },
  en: {
    title:'A day at your own pace',private:'Your learning plans are private',day:'Day',week:'Week',courses:'Courses',all:'All records',zone:'Display time zone',
    add:'Add',back:'Back',previous:'Previous',next:'Next',today:'Today',refresh:'Refresh',empty:'Nothing planned here yet.',
    event:'Schedule',task:'Task',note:'Private note',material:'Resource link',course:'Course',edit:'Edit',remove:'Delete',save:'Save',cancel:'Cancel',
    confirmDelete:'Delete this record?',detach:'Removing a course detaches its records. Your schedule, tasks and notes are kept.',
    name:'Title',code:'Course code (optional)',body:'Details (optional)',location:'Location (optional)',url:'Resource URL',
    courseChoice:'Linked course',noCourse:'No course',allDay:'All day',timed:'Specific time',date:'Start date',endDate:'End date (exclusive, optional)',
    start:'Start time',end:'End time (optional)',format:'Date: YYYY-MM-DD; time: YYYY-MM-DD HH:mm, in Hong Kong time.',
    due:'Deadline',noDue:'No deadline',dateDue:'Date only',timeDue:'Date and time',dueDate:'Due date',dueTime:'Due time',
    complete:'Mark done',reopen:'Reopen',done:'Done',open:'To do',active:'Active',cancelled:'Cancelled',cancelEvent:'Cancel schedule',restoreEvent:'Restore schedule',
    unknownEnd:'End time not provided',undated:'No deadline yet',viewLink:'Open resource',manual:'Personally maintained · Not official enrolment',
    loading:'Loading…',error:'Could not refresh. Existing records were kept. Please retry.',conflict:'This record changed. Go back, refresh, and edit the latest version. Your current draft has not been saved.',
    invalid:'Check the title, dates, times and URL.',saveError:'Could not save. Your draft is kept; try again.',
    allDayLabel:'All day',unconfirmed:'Record saved; refreshing your list.',
  },
};
